"""Update failure_modes and add root_causes in operational schema

Revision ID: b38017adcb3c
Revises: 808ca99ecda7
Create Date: 2024-11-07 15:12:42.984947+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b38017adcb3c"
down_revision: str | None = "808ca99ecda7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "root_causes",
        sa.Column("root_cause_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("device_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_type_id"],
            ["operational.device_types.device_type_id"],
        ),
        sa.PrimaryKeyConstraint("root_cause_id"),
        schema="operational",
    )
    op.add_column(
        "failure_modes",
        sa.Column("device_type_id", sa.SmallInteger(), nullable=True),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "failure_modes",
        "device_types",
        ["device_type_id"],
        ["device_type_id"],
        source_schema="operational",
        referent_schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "failure_modes", schema="operational", type_="foreignkey")
    op.drop_column("failure_modes", "device_type_id", schema="operational")
    op.drop_table("root_causes", schema="operational")
    # ### end Alembic commands ###
