"""Add failure_modes table

Revision ID: 316369becf70
Revises: 235f6feda4a3
Create Date: 2024-05-14 21:25:13.607661+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "316369becf70"
down_revision: str | None = "235f6feda4a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failure_modes",
        sa.Column("failure_mode_id", sa.Integer(), nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("failure_mode_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("failure_modes", schema="operational")
    # ### end Alembic commands ###
