"""Make kpi_types.device_type_id not null

Revision ID: 1394e5edac3a
Revises: 95e683a10b96
Create Date: 2024-09-05 17:05:05.657911+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1394e5edac3a"
down_revision: str | None = "95e683a10b96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "kpi_types",
        "device_type_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "kpi_types",
        "device_type_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="operational",
    )
    # ### end Alembic commands ###
