"""Drop operational.event_types

Revision ID: d765bd4477b5
Revises: bb18a5148c50
Create Date: 2024-11-07 17:16:30.198549+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d765bd4477b5"
down_revision: str | None = "bb18a5148c50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_types", schema="operational")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_types",
        sa.Column("event_type_id", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("device_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name_short", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name_long", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["device_type_id"],
            ["operational.device_types.device_type_id"],
            name="event_types_device_type_id_fkey",
        ),
        sa.PrimaryKeyConstraint("event_type_id", name="event_types_pkey"),
        schema="operational",
    )
    # ### end Alembic commands ###
