"""Remove parallel_source_circuits from project combiner tables

Revision ID: 979f24a37095
Revises: f55a8b6463f1
Create Date: 2024-12-20 19:00:00.470474+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "979f24a37095"
down_revision: str | None = "f55a8b6463f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_dc_combiners", "parallel_source_circuits", schema=schema)
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_dc_combiners",
        sa.Column(
            "parallel_source_circuits",
            sa.SMALLINT(),
            autoincrement=False,
            nullable=False,
        ),
        schema=schema,
    )
    # ### end Alembic commands ###
