"""Recreate kpi_alerts table with new ID

Revision ID: 376cea900e93
Revises: 48a5759b3e13
Create Date: 2024-07-29 20:50:03.206986+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "376cea900e93"
down_revision: str | None = "48a5759b3e13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_alerts",
        sa.Column("kpi_alert_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("kpi_type_id", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["kpi_type_id"],
            ["operational.kpi_types.kpi_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("kpi_alert_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kpi_alerts", schema="operational")
    # ### end Alembic commands ###
