"""added frame_overhang and has_ar_coating to pvmodule table

Revision ID: d4c66eb09f0e
Revises: 00e7b6561bbc
Create Date: 2024-11-27 18:30:13.428454+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4c66eb09f0e"
down_revision: str | None = "00e7b6561bbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_modules",
        sa.Column("frame_overhang", sa.Float(), server_default="0.0", nullable=False),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column(
            "has_ar_coating",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_modules", "has_ar_coating", schema="operational")
    op.drop_column("pv_modules", "frame_overhang", schema="operational")
    # ### end Alembic commands ###
