"""Add cod to operational.projects

Revision ID: 61c9053b4162
Revises: d765bd4477b5
Create Date: 2024-11-11 15:23:26.952550+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61c9053b4162"
down_revision: str | None = "d765bd4477b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("cod", sa.Date(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "cod", schema="operational")
    # ### end Alembic commands ###
