"""Add in_tsdb column to tags tables

Revision ID: b90a15b32dce
Revises: b6d552086d8f
Create Date: 2024-05-07 14:40:19.768521+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "b90a15b32dce"
down_revision: str | None = "b6d552086d8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tags",
        sa.Column("in_tsdb", sa.Boolean(), server_default="FALSE", nullable=False),
        schema=schema,
    )
    op.create_index(
        op.f("ix_tags_in_tsdb"),
        "tags",
        ["in_tsdb"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tags_in_tsdb"), table_name="tags", schema=schema)
    op.drop_column("tags", "in_tsdb", schema=schema)
    # ### end Alembic commands ###
