"""Change operational.trees full to all_devices_and_tags

Revision ID: 1a5b150d871e
Revises: fec4a69c4844
Create Date: 2024-08-29 15:40:43.764305+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1a5b150d871e"
down_revision: str | None = "fec4a69c4844"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trees",
        sa.Column(
            "all_devices_and_tags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        schema="operational",
    )
    op.drop_column("trees", "full", schema="operational")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trees",
        sa.Column(
            "full",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        schema="operational",
    )
    op.drop_column("trees", "all_devices_and_tags", schema="operational")
    # ### end Alembic commands ###
