"""Add admin.users.user_type_id

Revision ID: 5ebcdc85ab5b
Revises: b67321e94c23
Create Date: 2024-11-13 23:34:19.575394+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ebcdc85ab5b"
down_revision: str | None = "b67321e94c23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "user_type_id",
            sa.SmallInteger(),
            server_default="3",
            nullable=False,
        ),
        schema="admin",
    )
    op.create_foreign_key(
        None,
        "users",
        "user_types",
        ["user_type_id"],
        ["user_type_id"],
        source_schema="admin",
        referent_schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", schema="admin", type_="foreignkey")
    op.drop_column("users", "user_type_id", schema="admin")
    # ### end Alembic commands ###
