"""Add admin.user_projects

Revision ID: 25410bf19dee
Revises: f36bf2c5411d
Create Date: 2024-11-14 00:06:26.636325+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25410bf19dee"
down_revision: str | None = "f36bf2c5411d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_projects",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("operational_project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operational_project_id"],
            ["operational.projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "operational_project_id"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_projects", schema="admin")
    # ### end Alembic commands ###
