"""Add modules_per_combiner column to pv_dc_combiners table

Revision ID: 417be9e9ecd4
Revises: 9ec1f065b1b4
Create Date: 2024-11-05 18:54:15.160319+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "417be9e9ecd4"
down_revision: str | None = "9ec1f065b1b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_dc_combiners",
        sa.Column("modules_per_combiner", sa.SmallInteger(), nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_dc_combiners", "modules_per_combiner", schema=schema)
    # ### end Alembic commands ###
