"""Add admin.user_types

Revision ID: b67321e94c23
Revises: 346d28adecc3
Create Date: 2024-11-13 23:31:13.173527+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b67321e94c23"
down_revision: str | None = "346d28adecc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_types",
        sa.Column(
            "user_type_id",
            sa.SmallInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_type_id"),
        sa.UniqueConstraint("name_short"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_types", schema="admin")
    # ### end Alembic commands ###
