"""added pv_modules_table

Revision ID: d94e6195363e
Revises: ebce8cb0a2b5
Create Date: 2024-11-12 18:12:05.076861+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d94e6195363e"
down_revision: str | None = "ebce8cb0a2b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pv_modules",
        sa.Column("pv_module_id", sa.Integer(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("technology", sa.String(), nullable=False),
        sa.Column("bifacial", sa.Boolean(), nullable=False),
        sa.Column("pmax", sa.Float(), nullable=False),
        sa.Column("isc", sa.Float(), nullable=False),
        sa.Column("voc", sa.Float(), nullable=False),
        sa.Column("imp", sa.Float(), nullable=False),
        sa.Column("vmp", sa.Float(), nullable=False),
        sa.Column("gamma_pmax", sa.Float(), nullable=False),
        sa.Column("alpha_isc", sa.Float(), nullable=False),
        sa.Column("beta_voc", sa.Float(), nullable=False),
        sa.Column("warranted_degradation_rate", sa.Float(), nullable=False),
        sa.Column("warranted_degradation_initial", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("pv_module_id"),
        sa.UniqueConstraint("manufacturer", "model"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pv_modules", schema="operational")
    # ### end Alembic commands ###
