"""Add has_met_stations, has_bess_blocks, has_bess_pcss to operational.projects table

Revision ID: e97e3ef7f016
Revises: da8a8c007240
Create Date: 2024-09-26 22:42:14.739598+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e97e3ef7f016"
down_revision: str | None = "da8a8c007240"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "has_met_stations",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column(
            "has_bess_blocks",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column(
            "has_bess_pcss",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "has_bess_pcss", schema="operational")
    op.drop_column("projects", "has_bess_blocks", schema="operational")
    op.drop_column("projects", "has_met_stations", schema="operational")
    # ### end Alembic commands ###
