"""Add has_maximo_integration and has_quality_integration columns to projects table

Revision ID: 908ca9138756
Revises: 1394e5edac3a
Create Date: 2024-09-06 14:22:42.191439+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "908ca9138756"
down_revision: str | None = "1394e5edac3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "has_maximo_integration",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column(
            "has_quality_integration",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "has_quality_integration", schema="operational")
    op.drop_column("projects", "has_maximo_integration", schema="operational")
    # ### end Alembic commands ###
