"""Add kpi_types table

Revision ID: c3b5581e3478
Revises: 07f1b4ccd632
Create Date: 2024-01-24 23:04:17.717672+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3b5581e3478"
down_revision: str | None = "07f1b4ccd632"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_types",
        sa.Column("kpi_type_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("aggregation_method", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("kpi_type_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kpi_types", schema="operational")
    # ### end Alembic commands ###
