"""Add completed field to feedback table

Revision ID: ffcf12930286
Revises: bbecad2fe5e9
Create Date: 2024-06-12 16:03:53.665066+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffcf12930286"
down_revision: str | None = "bbecad2fe5e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feedback",
        sa.Column("completed", sa.Boolean(), server_default="false", nullable=False),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedback", "completed", schema="admin")
    # ### end Alembic commands ###
