"""Remove sced_load table

Revision ID: 2a0a76a2ae74
Revises: 275f15769a30
Create Date: 2024-01-15 19:12:56.579144+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2a0a76a2ae74"
down_revision: str | None = "275f15769a30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sced_load", schema="ercot")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sced_load",
        sa.Column(
            "time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "settlement_point_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "power_consumed",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["settlement_point_id"],
            ["ercot.settlement_points.settlement_point_id"],
            name="sced_load_settlement_point_id_fkey",
        ),
        sa.PrimaryKeyConstraint("time", "settlement_point_id", name="sced_load_pkey"),
        schema="ercot",
    )
    # ### end Alembic commands ###
