"""Add root_causes table

Revision ID: 8b51454dc0e5
Revises: b90a15b32dce
Create Date: 2024-05-13 20:51:32.099267+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b51454dc0e5"
down_revision: str | None = "b90a15b32dce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "root_causes",
        sa.Column("root_cause_id", sa.Integer(), nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("root_cause_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("root_causes", schema="operational")
    # ### end Alembic commands ###
