"""Add description field to operational.kpi_types

Revision ID: 312bbfe1263b
Revises: 6b5edf12ac75
Create Date: 2024-07-16 22:54:39.820730+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "312bbfe1263b"
down_revision: str | None = "6b5edf12ac75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kpi_types",
        sa.Column("description", sa.String(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kpi_types", "description", schema="operational")
    # ### end Alembic commands ###
