"""Add failure_mode_id field to events tables

Revision ID: 21c8b110c2c4
Revises: 4e0ef78fe236
Create Date: 2024-05-14 22:06:35.348140+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "21c8b110c2c4"
down_revision: str | None = "4e0ef78fe236"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("failure_mode_id", sa.Integer(), server_default="1", nullable=False),
        schema=schema,
    )
    op.create_foreign_key(
        None,
        "events",
        "failure_modes",
        ["failure_mode_id"],
        ["failure_mode_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", schema=schema, type_="foreignkey")
    op.drop_column("events", "failure_mode_id", schema=schema)
    # ### end Alembic commands ###
