"""Add sced_load table

Revision ID: 3ffeeeb8f7d6
Revises: 2a0a76a2ae74
Create Date: 2024-01-15 19:15:46.890130+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ffeeeb8f7d6"
down_revision: str | None = "2a0a76a2ae74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sced_load",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("power_consumed", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["ercot.resources.resource_id"],
        ),
        sa.PrimaryKeyConstraint("time", "resource_id"),
        schema="ercot",
    )
    op.execute(
        """
        SELECT create_hypertable('ercot.sced_load', 'time');
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sced_load", schema="ercot")
    # ### end Alembic commands ###
