"""Add NOT NULL constraint to admin.users.company_id

Revision ID: ad7edf5ed267
Revises: ed6f7f232d4f
Create Date: 2024-10-22 17:32:27.227699+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad7edf5ed267"
down_revision: str | None = "ed6f7f232d4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "company_id",
        existing_type=sa.UUID(),
        nullable=False,
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "company_id",
        existing_type=sa.UUID(),
        nullable=True,
        schema="admin",
    )
    # ### end Alembic commands ###
