"""Make sensor_types.device_type_id NOT NULL

Revision ID: 233135088c28
Revises: aead980be11e
Create Date: 2025-09-16 23:11:30.104961+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "233135088c28"
down_revision: str | None = "aead980be11e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sensor_types",
        "device_type_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sensor_types",
        "device_type_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="operational",
    )
    # ### end Alembic commands ###
