"""remove has_maximo_integration from projects table

Revision ID: 748991eaf15d
Revises: 61bf8f42726f
Create Date: 2025-06-17 19:39:20.111393+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "748991eaf15d"
down_revision: str | None = "61bf8f42726f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "has_maximo_integration", schema="operational")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "has_maximo_integration",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###
