"""Add family column to pv_modules table

Revision ID: 7b9764436f96
Revises: e68b7e364b0b
Create Date: 2025-03-05 21:39:41.138891+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b9764436f96"
down_revision: str | None = "e68b7e364b0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_modules",
        sa.Column("family", sa.String(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_modules", "family", schema="operational")
    # ### end Alembic commands ###
