"""Make project.address NOT NULL

Revision ID: 82a1f657624d
Revises: 82d3bb3ce304
Create Date: 2025-08-01 21:50:20.435144+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82a1f657624d"
down_revision: str | None = "82d3bb3ce304"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "address",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "address",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="operational",
    )
    # ### end Alembic commands ###
