"""Make operational.projects.polygon nullable

Revision ID: 3df92db73b84
Revises: 8fbe37f86d6c
Create Date: 2025-06-13 21:00:19.695787+00:00

"""

from collections.abc import Sequence

import geoalchemy2
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3df92db73b84"
down_revision: str | None = "8fbe37f86d6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "polygon",
        existing_type=geoalchemy2.types.Geography(
            srid=4326, from_text="ST_GeogFromText", name="geography", nullable=False
        ),
        nullable=True,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "polygon",
        existing_type=geoalchemy2.types.Geography(
            srid=4326, from_text="ST_GeogFromText", name="geography", nullable=False
        ),
        nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###
