"""expected energy version

Revision ID: 5e803952cd8b
Revises: 4f54ece41407
Create Date: 2025-04-09 21:54:11.364877+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e803952cd8b"
down_revision: str | None = "4f54ece41407"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expected_versions",
        sa.Column(
            "expected_version_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("major", sa.Integer(), nullable=False),
        sa.Column("minor", sa.Integer(), nullable=False),
        sa.Column("patch", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("expected_version_id"),
        sa.UniqueConstraint("major", "minor", "patch", name="unique_expected_version"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expected_versions", schema="operational")
    # ### end Alembic commands ###
