"""Add CalendarItemCategory model and update CalendarItem FK

Revision ID: b0b2ec533da4
Revises: c2b328f00beb
Create Date: 2025-05-07 17:46:08.788832+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0b2ec533da4"
down_revision: str | None = "c2b328f00beb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_item_categories",
        sa.Column(
            "category_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("short_name", sa.Text(), nullable=False),
        sa.Column("long_name", sa.Text(), nullable=False),
        sa.Column("color_code", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("category_id"),
        sa.UniqueConstraint("long_name"),
        sa.UniqueConstraint("short_name"),
        schema="operational",
    )
    op.create_table(
        "calendar_items",
        sa.Column(
            "calendar_item_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("calendar_item_category_id", sa.UUID(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("all_day", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("rrule", sa.Text(), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calendar_item_category_id"],
            ["operational.calendar_item_categories.category_id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("calendar_item_id"),
        schema="operational",
    )
    op.create_index(
        "calendar_items_company_id_start_time_idx",
        "calendar_items",
        ["company_id", "start_time"],
        unique=False,
        schema="operational",
    )
    op.create_index(
        "calendar_items_project_id_start_time_idx",
        "calendar_items",
        ["project_id", "start_time"],
        unique=False,
        schema="operational",
    )
    op.create_table(
        "calendar_item_exceptions",
        sa.Column(
            "exception_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("calendar_item_id", sa.UUID(), nullable=False),
        sa.Column("exception_date", sa.Date(), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("override_start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("override_end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calendar_item_id"],
            ["operational.calendar_items.calendar_item_id"],
        ),
        sa.PrimaryKeyConstraint("exception_id"),
        sa.UniqueConstraint(
            "calendar_item_id",
            "exception_date",
            name="uq_calendar_item_exception_date",
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_item_exceptions", schema="operational")
    op.drop_index(
        "calendar_items_project_id_start_time_idx",
        table_name="calendar_items",
        schema="operational",
    )
    op.drop_index(
        "calendar_items_company_id_start_time_idx",
        table_name="calendar_items",
        schema="operational",
    )
    op.drop_table("calendar_items", schema="operational")
    op.drop_table("calendar_item_categories", schema="operational")
    # ### end Alembic commands ###
