"""Add has_trackers to projects table

Revision ID: 8b4829cd5076
Revises: 7ce035abffd3
Create Date: 2025-01-21 17:13:30.070547+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b4829cd5076"
down_revision: str | None = "7ce035abffd3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("has_trackers", sa.Boolean(), server_default="FALSE", nullable=False),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "has_trackers", schema="operational")
    # ### end Alembic commands ###
