"""status added to operational.projects

Revision ID: 39bcecb668f2
Revises: f157bfe012f3
Create Date: 2025-06-18 21:49:41.925751+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39bcecb668f2"
down_revision: str | None = "f157bfe012f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#   `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_status_types",
        sa.Column(
            "project_status_type_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("project_status_type_id"),
        sa.UniqueConstraint("name_long"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("project_status_type_id", sa.Integer(), nullable=True),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "projects",
        "project_status_types",
        ["project_status_type_id"],
        ["project_status_type_id"],
        source_schema="operational",
        referent_schema="operational",
    )
    op.create_unique_constraint(
        None, "rackings", ["manufacturer", "model", "company_id"], schema="operational"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rackings", schema="operational", type_="unique")
    op.drop_constraint(None, "projects", schema="operational", type_="foreignkey")
    op.drop_column("projects", "project_status_type_id", schema="operational")
    op.drop_table("project_status_types", schema="operational")
    # ### end Alembic commands ###
