"""remove maximo_assetnum from devices

Revision ID: a149bf6204da
Revises: ff69879136a5
Create Date: 2025-06-03 16:25:06.589643+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "a149bf6204da"
down_revision: str | None = "ff69879136a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "maximo_assetnum", schema=schema)
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("maximo_assetnum", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###
