"""Add operational.device_models

Revision ID: ff59c3ed62d7
Revises: 8c0b7607756a
Create Date: 2025-09-21 20:29:30.080223+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff59c3ed62d7"
down_revision: str | None = "8c0b7607756a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_models",
        sa.Column("device_model_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_type_id", sa.Integer(), nullable=False),
        sa.Column("brand", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_type_id"],
            ["operational.device_types.device_type_id"],
        ),
        sa.PrimaryKeyConstraint("device_model_id"),
        sa.UniqueConstraint(
            "device_type_id",
            "brand",
            "model",
            name="uq_device_models_device_type_id_brand_model",
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("device_models", schema="operational")
    # ### end Alembic commands ###
