"""Add inverter efficiency reference parameters to inverter table

Revision ID: 234e0a7e2316
Revises: 8b4829cd5076
Create Date: 2025-01-27 17:37:42.522086+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "234e0a7e2316"
down_revision: str | None = "8b4829cd5076"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inverters",
        sa.Column("voltage_nominal_efficiency", sa.ARRAY(sa.Float()), nullable=False),
        schema="operational",
    )
    op.add_column(
        "inverters",
        sa.Column("efficiency_at_low_voltage", sa.ARRAY(sa.Float()), nullable=False),
        schema="operational",
    )
    op.add_column(
        "inverters",
        sa.Column("efficiency_at_mid_voltage", sa.ARRAY(sa.Float()), nullable=False),
        schema="operational",
    )
    op.add_column(
        "inverters",
        sa.Column("efficiency_at_high_voltage", sa.ARRAY(sa.Float()), nullable=False),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inverters", "efficiency_at_high_voltage", schema="operational")
    op.drop_column("inverters", "efficiency_at_mid_voltage", schema="operational")
    op.drop_column("inverters", "efficiency_at_low_voltage", schema="operational")
    op.drop_column("inverters", "voltage_nominal_efficiency", schema="operational")
    # ### end Alembic commands ###
