"""Make capacity_bess_power_ac and _energy_bol_dc not null with defaults of 0

Revision ID: c82d6ac92e51
Revises: 82a1f657624d
Create Date: 2025-08-01 22:52:23.368076+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c82d6ac92e51"
down_revision: str | None = "82a1f657624d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "capacity_bess_power_ac",
        existing_type=sa.REAL(),
        nullable=False,
        server_default="0",
        schema="operational",
    )
    op.alter_column(
        "projects",
        "capacity_bess_energy_bol_dc",
        existing_type=sa.REAL(),
        nullable=False,
        server_default="0",
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "capacity_bess_energy_bol_dc",
        existing_type=sa.REAL(),
        nullable=True,
        server_default=None,
        schema="operational",
    )
    op.alter_column(
        "projects",
        "capacity_bess_power_ac",
        existing_type=sa.REAL(),
        nullable=True,
        server_default=None,
        schema="operational",
    )
    # ### end Alembic commands ###
