"""Add NOT NULL constraint to name_metric in kpi_types

Revision ID: e6852416cfa4
Revises: b6c86cf21bfc
Create Date: 2025-04-03 18:10:34.552892+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6852416cfa4"
down_revision: str | None = "b6c86cf21bfc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "kpi_types",
        "name_metric",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "kpi_types",
        "name_metric",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="operational",
    )
    # ### end Alembic commands ###
