"""Add version column to operational.kpi_data table

Revision ID: 1d8e42ad80c6
Revises: bfadcc9bf14f
Create Date: 2025-02-06 23:44:13.118170+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d8e42ad80c6"
down_revision: str | None = "bfadcc9bf14f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kpi_data",
        sa.Column("version", sa.String(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kpi_data", "version", schema="operational")
    # ### end Alembic commands ###
