"""add voltage_ac_nominal to inverter table

Revision ID: 150b38f615ff
Revises: a65ac72eed54
Create Date: 2025-07-25 18:09:07.343853+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "150b38f615ff"
down_revision: str | None = "a65ac72eed54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inverters",
        sa.Column("voltage_ac_nominal", sa.Float(), nullable=True, comment="[V]"),
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "power_start_up",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="[W]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "power_ac_nominal",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="[W]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "power_dc_nominal",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="[W]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "voltage_dc_nominal",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="[V]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "c0",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="[unitless]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "c1",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="[unitless]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "c2",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="[unitless]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "c3",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="[unitless]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "night_tare",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="[W]",
        existing_nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inverters",
        "night_tare",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="[W]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "c3",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="[unitless]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "c2",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="[unitless]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "c1",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="[unitless]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "c0",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="[unitless]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "voltage_dc_nominal",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="[V]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "power_dc_nominal",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="[W]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "power_ac_nominal",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="[W]",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "inverters",
        "power_start_up",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="[W]",
        existing_nullable=False,
        schema="operational",
    )
    op.drop_column("inverters", "voltage_ac_nominal", schema="operational")
    # ### end Alembic commands ###
