"""remove deprecated columns from operational
- projects.active
- projects.is_commissioning
- projects.capacity_power
- pv_modules.bifacial

Revision ID: e5a83b2398b9
Revises: 6e3340188785
Create Date: 2025-08-26 22:42:25.677146+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5a83b2398b9"
down_revision: str | None = "6e3340188785"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "active", schema="operational")
    op.drop_column("projects", "capacity_power", schema="operational")
    op.drop_column("projects", "is_commissioning", schema="operational")
    op.drop_column("pv_modules", "bifacial", schema="operational")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_modules",
        sa.Column("bifacial", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column(
            "is_commissioning",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("capacity_power", sa.REAL(), autoincrement=False, nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column(
            "active",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###
