"""add nominal_state to status_boolean and status_binary tables

Revision ID: f157bfe012f3
Revises: 748991eaf15d
Create Date: 2025-06-18 12:48:57.610747+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f157bfe012f3"
down_revision: str | None = "748991eaf15d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "status_binary",
        sa.Column("nominal_state", sa.Boolean(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "status_boolean",
        sa.Column("nominal_state", sa.Boolean(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("status_boolean", "nominal_state", schema="operational")
    op.drop_column("status_binary", "nominal_state", schema="operational")
    # ### end Alembic commands ###
