"""Adding inverters table

Revision ID: cacdfc0b8ea0
Revises: e6fe6ee493d8
Create Date: 2025-01-09 02:42:52.700435+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cacdfc0b8ea0"
down_revision: str | None = "e6fe6ee493d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inverters",
        sa.Column("inverter_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("voltage_mpp_min", sa.Float(), nullable=False),
        sa.Column("voltage_mpp_max", sa.Float(), nullable=False),
        sa.Column("voltage_start_up", sa.Float(), nullable=False),
        sa.Column("voltage_min", sa.Float(), nullable=False),
        sa.Column("voltage_max", sa.Float(), nullable=False),
        sa.Column("current_max", sa.Float(), nullable=False),
        sa.Column("power_max_at_reference_temp", sa.ARRAY(sa.Float()), nullable=False),
        sa.Column("reference_temp", sa.ARRAY(sa.Float()), nullable=False),
        sa.Column("power_ac_nominal", sa.Float(), nullable=False),
        sa.Column("power_dc_nominal", sa.Float(), nullable=False),
        sa.Column("voltage_dc_nominal", sa.Float(), nullable=False),
        sa.Column("c0", sa.Float(), nullable=False),
        sa.Column("c1", sa.Float(), nullable=False),
        sa.Column("c2", sa.Float(), nullable=False),
        sa.Column("c3", sa.Float(), nullable=False),
        sa.Column("night_tare", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "array_length(power_max_at_reference_temp, 1) = "
            "array_length(reference_temp, 1)",
            name="check_power_temp_arrays_length",
        ),
        sa.PrimaryKeyConstraint("inverter_id"),
        sa.UniqueConstraint("manufacturer", "model"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inverters", schema="operational")
    # ### end Alembic commands ###
