"""Add operational.cmms_providers table

Revision ID: 3565d3258a23
Revises: 5e803952cd8b
Create Date: 2025-04-17 21:51:26.539810+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3565d3258a23"
down_revision: str | None = "5e803952cd8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cmms_providers",
        sa.Column(
            "cmms_provider_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("cmms_provider_id"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cmms_providers", schema="operational")
    # ### end Alembic commands ###
