"""Add doc_url column to kpi_types and report_types tables

Revision ID: 9427f6331493
Revises: 81df5e3b03d3
Create Date: 2025-02-24 03:35:38.126113+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9427f6331493"
down_revision: str | None = "81df5e3b03d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kpi_types",
        sa.Column("doc_url", sa.String(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "report_types",
        sa.Column("doc_url", sa.String(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_types", "doc_url", schema="operational")
    op.drop_column("kpi_types", "doc_url", schema="operational")
    # ### end Alembic commands ###
