"""make source id and cmms integration id unique pairs

Revision ID: 6f8b6ee68711
Revises: 6338b5243c1b
Create Date: 2025-09-26 17:09:05.757339+00:00

"""

from collections.abc import Sequence

from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "6f8b6ee68711"
down_revision: str | None = "6338b5243c1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "cmms_tickets_integration_source_unique",
        "cmms_tickets",
        ["cmms_integration_id", "source_id"],
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "cmms_tickets_integration_source_unique",
        "cmms_tickets",
        schema=schema,
        type_="unique",
    )
    # ### end Alembic commands ###
