# Custom Nginx Configuration
proxy_buffer_size   128k;
proxy_buffers   4 128k;
proxy_busy_buffers_size   256k;
client_max_body_size 40M;

# --- Gzip Compression ---
gzip on;
gzip_vary on;
gzip_proxied any;
gzip_min_length 1024;
gzip_comp_level 5;

gzip_types
    text/plain
    text/css
    application/json
    application/problem+json
    application/javascript
    application/xml
    application/rss+xml
    image/svg+xml;
gzip_disable "msie6";
