# For testing locally
services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CODEARTIFACT_TOKEN: ${AWS_CODEARTIFACT_TOKEN}
    ports:
      - "9000:8080"
    # mounts AWS credentials from local
    volumes:
      - ~/.aws:/root/.aws
