"""Add reviewed column to admin.feedback table

Revision ID: da8a8c007240
Revises: 908ca9138756
Create Date: 2024-09-18 16:36:10.141067+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da8a8c007240"
down_revision: str | None = "908ca9138756"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feedback",
        sa.Column("reviewed", sa.Boolean(), server_default="false", nullable=False),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedback", "reviewed", schema="admin")
    # ### end Alembic commands ###
