"""Add pv_dc_combiners tables

Revision ID: 811913774182
Revises: b36ded8226ab
Create Date: 2024-10-15 16:59:31.705056+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "811913774182"
down_revision: str | None = "b36ded8226ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pv_dc_combiners",
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("parallel_source_circuits", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            [f"{schema}.devices.device_id"],
        ),
        sa.PrimaryKeyConstraint("device_id"),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pv_dc_combiners", schema=schema)
    # ### end Alembic commands ###
