"""single diode reference parameters

Revision ID: 25acbd263ca3
Revises: d4c66eb09f0e
Create Date: 2024-12-02 15:33:33.157623+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25acbd263ca3"
down_revision: str | None = "d4c66eb09f0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_modules",
        sa.Column(
            "cells_in_series",
            sa.SmallInteger(),
            server_default="72",
            nullable=False,
        ),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("photocurrent", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("diode_saturation_current", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("r_series", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("r_shunt", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("modified_ideality_factor", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("eg", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("degdt", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("data_source", sa.String(), server_default="CEC", nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_modules", "data_source", schema="operational")
    op.drop_column("pv_modules", "degdt", schema="operational")
    op.drop_column("pv_modules", "eg", schema="operational")
    op.drop_column("pv_modules", "modified_ideality_factor", schema="operational")
    op.drop_column("pv_modules", "r_shunt", schema="operational")
    op.drop_column("pv_modules", "r_series", schema="operational")
    op.drop_column("pv_modules", "diode_saturation_current", schema="operational")
    op.drop_column("pv_modules", "photocurrent", schema="operational")
    op.drop_column("pv_modules", "cells_in_series", schema="operational")
    # ### end Alembic commands ###
