"""Add data_raw table to project schema

Revision ID: 6b5edf12ac75
Revises: f06cd1373b56
Create Date: 2024-07-09 15:35:02.468108+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b5edf12ac75"
down_revision: str | None = "f06cd1373b56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_raw",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("value_continuous", sa.Double(), nullable=True),
        sa.Column("value_boolean", sa.Boolean(), nullable=True),
        sa.Column("value_cumulative", sa.BigInteger(), nullable=True),
        sa.Column("value_string", sa.String(), nullable=True),
        sa.Column("value_status", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            [f"{schema}.tags.tag_id"],
        ),
        sa.PrimaryKeyConstraint("time", "tag_id"),
        schema=schema,
    )
    op.create_index(
        "data_raw_tag_id_time_idx",
        "data_raw",
        ["tag_id", sa.text("time DESC")],
        unique=False,
        schema=schema,
    )
    op.execute(
        f"""
        SELECT create_hypertable(
            '{schema}.data_raw',
            by_range('time', INTERVAL '1 day')
        );
        """,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("data_raw_tag_id_time_idx", table_name="data_raw", schema=schema)
    op.drop_table("data_raw", schema=schema)
    # ### end Alembic commands ###
