"""Remove NOT NULL constraint from events.event_type_id field

Revision ID: 72734278c7d3
Revises: ffcf12930286
Create Date: 2024-06-19 15:30:48.276726+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72734278c7d3"
down_revision: str | None = "ffcf12930286"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "event_type_id",
        existing_type=sa.SMALLINT(),
        nullable=True,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "event_type_id",
        existing_type=sa.SMALLINT(),
        nullable=False,
        schema=schema,
    )
    # ### end Alembic commands ###
