"""Add user_subscriptions table

Revision ID: 6ca0b742e20e
Revises: 561951348fb6
Create Date: 2024-06-05 16:47:53.405833+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ca0b742e20e"
down_revision: str | None = "561951348fb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_subscriptions",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("operational_project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "notifications",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("reports", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["operational_project_id"],
            ["operational.projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "operational_project_id"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_subscriptions", schema="admin")
    # ### end Alembic commands ###
