"""add length and width to PVModule table

Revision ID: 00e7b6561bbc
Revises: 1abe5ee70034
Create Date: 2024-11-26 15:13:53.389171+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00e7b6561bbc"
down_revision: str | None = "1abe5ee70034"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_modules",
        sa.Column("length", sa.Float(), server_default="2.0", nullable=False),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("width", sa.Float(), server_default="1.0", nullable=False),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_modules", "width", schema="operational")
    op.drop_column("pv_modules", "length", schema="operational")
    # ### end Alembic commands ###
