"""Add is_outage and root_cause_id fields to events tables

Revision ID: dfdbe1df97d7
Revises: 8b51454dc0e5
Create Date: 2024-05-13 21:43:40.131811+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfdbe1df97d7"
down_revision: str | None = "8b51454dc0e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("is_outage", sa.Boolean(), server_default="TRUE", nullable=False),
        schema=schema,
    )
    op.add_column(
        "events",
        sa.Column("root_cause_id", sa.Integer(), server_default="1", nullable=False),
        schema=schema,
    )
    op.create_foreign_key(
        None,
        "events",
        "root_causes",
        ["root_cause_id"],
        ["root_cause_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", schema=schema, type_="foreignkey")
    op.drop_column("events", "root_cause_id", schema=schema)
    op.drop_column("events", "is_outage", schema=schema)
    # ### end Alembic commands ###
