"""Add users and user_permissions tables

Revision ID: 576e68812efc
Revises: 8cbc0333d8ec
Create Date: 2024-01-12 19:29:26.732119+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "576e68812efc"
down_revision: str | None = "8cbc0333d8ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("api_key"),
        schema="admin",
    )
    op.create_table(
        "user_permissions",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("operational_project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operational_project_id"],
            ["operational.projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "operational_project_id"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_permissions", schema="admin")
    op.drop_table("users", schema="admin")
    # ### end Alembic commands ###
