"""Add operational.trees table

Revision ID: fec4a69c4844
Revises: 343a983f060f
Create Date: 2024-08-29 15:24:46.687586+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fec4a69c4844"
down_revision: str | None = "343a983f060f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trees",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("full", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("project_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trees", schema="operational")
    # ### end Alembic commands ###
