"""Add data_table column to operational.projects table

Revision ID: 4485eb3cb2f6
Revises: 979f24a37095
Create Date: 2024-12-23 18:09:20.308202+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4485eb3cb2f6"
down_revision: str | None = "979f24a37095"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("data_table", sa.String(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "data_table", schema="operational")
    # ### end Alembic commands ###
