"""Drop pdf_reports tables

Revision ID: bce358c6c74d
Revises: 1a5d0b6f51cd
Create Date: 2024-03-20 23:04:19.137375+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bce358c6c74d"
down_revision: str | None = "1a5d0b6f51cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pdf_reports", schema=schema)
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pdf_reports",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("data", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("name", name="pdf_reports_pkey"),
        schema=schema,
    )
    # ### end Alembic commands ###
