"""Add has_pv_pcs_modules to projects table

Revision ID: bbecad2fe5e9
Revises: 6ca0b742e20e
Create Date: 2024-06-10 22:14:19.789198+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbecad2fe5e9"
down_revision: str | None = "6ca0b742e20e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "has_pv_pcs_modules",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "has_pv_pcs_modules", schema="operational")
    # ### end Alembic commands ###
