"""Add data_expected table to project schemas

Revision ID: da6b28647342
Revises: 633b78a0f2c8
Create Date: 2024-12-10 22:34:20.151700+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "da6b28647342"
down_revision: str | None = "633b78a0f2c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_expected",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("expected_metric_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            [f"{schema}.devices.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["expected_metric_id"],
            ["operational.expected_metrics.expected_metric_id"],
        ),
        sa.PrimaryKeyConstraint("time", "device_id", "expected_metric_id"),
        schema=schema,
    )
    op.execute(
        f"""
        SELECT create_hypertable('{schema}.data_expected', by_range('time'));
        """,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_expected", schema=schema)
    # ### end Alembic commands ###
