"""Enforce not null on pv_dc_combiners.modules_per_pv_source_circuit

Revision ID: 074c52092d44
Revises: bb54d9b2c547
Create Date: 2024-10-15 19:24:27.753284+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "074c52092d44"
down_revision: str | None = "bb54d9b2c547"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pv_dc_combiners",
        "modules_per_pv_source_circuit",
        existing_type=sa.SMALLINT(),
        nullable=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pv_dc_combiners",
        "modules_per_pv_source_circuit",
        existing_type=sa.SMALLINT(),
        nullable=True,
        schema=schema,
    )
    # ### end Alembic commands ###
