"""Add total_loss_financial to event tables

Revision ID: 343a983f060f
Revises: c82038e0ae9b
Create Date: 2024-08-08 19:30:12.764286+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "343a983f060f"
down_revision: str | None = "c82038e0ae9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("loss_total_financial", sa.Double(), nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "loss_total_financial", schema=schema)
    # ### end Alembic commands ###
