"""Add feedback table

Revision ID: 5f910ce1fe2d
Revises: c3a438df5c4e
Create Date: 2024-04-04 18:22:20.380909+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5f910ce1fe2d"
down_revision: str | None = "c3a438df5c4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("feedback_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("screenshot", postgresql.BYTEA(), nullable=True),
        sa.Column("screenshot_filename", sa.String(), nullable=True),
        sa.Column("screenshot_mimetype", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
        schema="admin",
    )
    op.create_index(
        op.f("ix_admin_feedback_user_id"),
        "feedback",
        ["user_id"],
        unique=False,
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_admin_feedback_user_id"),
        table_name="feedback",
        schema="admin",
    )
    op.drop_table("feedback", schema="admin")
    # ### end Alembic commands ###
