"""Add json field to kpi_data tables, make value field optional

Revision ID: c48322abc6bf
Revises: 81a2b2cb9fec
Create Date: 2024-03-01 22:42:33.521428+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c48322abc6bf"
down_revision: str | None = "81a2b2cb9fec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kpi_data",
        sa.Column("json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema=schema,
    )
    op.alter_column(
        "kpi_data",
        "value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "kpi_data",
        "value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        schema=schema,
    )
    op.drop_column("kpi_data", "json", schema=schema)
    # ### end Alembic commands ###
