"""Add company_id to admin.users

Revision ID: ed6f7f232d4f
Revises: 9bff4b3b50ca
Create Date: 2024-10-22 17:13:43.715583+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed6f7f232d4f"
down_revision: str | None = "9bff4b3b50ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("company_id", sa.UUID(), nullable=True),
        schema="admin",
    )
    op.create_foreign_key(
        None,
        "users",
        "companies",
        ["company_id"],
        ["company_id"],
        source_schema="admin",
        referent_schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", schema="admin", type_="foreignkey")
    op.drop_column("users", "company_id", schema="admin")
    # ### end Alembic commands ###
