"""Add initial ercot tables

Revision ID: df2adc2e3874
Revises: 98bacf75e0b3
Create Date: 2024-01-15 16:15:02.828473+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df2adc2e3874"
down_revision: str | None = "98bacf75e0b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dmes",
        sa.Column("dme_id", sa.Integer(), nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("dme_id"),
        sa.UniqueConstraint("name_short"),
        schema="ercot",
    )
    op.create_table(
        "qses",
        sa.Column("qse_id", sa.Integer(), nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("qse_id"),
        sa.UniqueConstraint("name_short"),
        schema="ercot",
    )
    op.create_table(
        "settlement_point_markets",
        sa.Column(
            "settlement_point_market_id",
            sa.SmallInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("settlement_point_market_id"),
        sa.UniqueConstraint("name_long"),
        sa.UniqueConstraint("name_short"),
        schema="ercot",
    )
    op.create_table(
        "settlement_point_types",
        sa.Column(
            "settlement_point_type_id",
            sa.SmallInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("settlement_point_type_id"),
        sa.UniqueConstraint("name_long"),
        sa.UniqueConstraint("name_short"),
        schema="ercot",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settlement_point_types", schema="ercot")
    op.drop_table("settlement_point_markets", schema="ercot")
    op.drop_table("qses", schema="ercot")
    op.drop_table("dmes", schema="ercot")
    # ### end Alembic commands ###
