"""Add project_types, data_types, sensor_types, and device_types tables

Revision ID: 8c3bb646d04f
Revises:
Create Date: 2024-01-12 18:54:27.543987+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c3bb646d04f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_types",
        sa.Column(
            "data_type_id",
            sa.SmallInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("data_type_id"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    op.create_table(
        "device_types",
        sa.Column("device_type_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("device_type_id"),
        sa.UniqueConstraint("name_long"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    op.create_table(
        "project_types",
        sa.Column(
            "project_type_id",
            sa.SmallInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("project_type_id"),
        sa.UniqueConstraint("name_long"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    op.create_table(
        "sensor_types",
        sa.Column("sensor_type_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.Column("name_metric", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("sensor_type_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensor_types", schema="operational")
    op.drop_table("project_types", schema="operational")
    op.drop_table("device_types", schema="operational")
    op.drop_table("data_types", schema="operational")
    # ### end Alembic commands ###
