"""Add pg_data_type_id to project tag tables

Revision ID: 8bf14dcc0a59
Revises: 4fff41176534
Create Date: 2024-12-23 21:54:32.818926+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bf14dcc0a59"
down_revision: str | None = "4fff41176534"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tags",
        sa.Column(
            "pg_data_type_id",
            sa.SmallInteger(),
            server_default="0",
            nullable=False,
        ),
        schema=schema,
    )
    op.create_foreign_key(
        None,
        "tags",
        "pg_data_types",
        ["pg_data_type_id"],
        ["pg_data_type_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", schema=schema, type_="foreignkey")
    op.drop_column("tags", "pg_data_type_id", schema=schema)
    # ### end Alembic commands ###
