"""Add maximo_assetnum field to project device tables

Revision ID: 372df4da6a50
Revises: fe4e5f71e14b
Create Date: 2024-03-31 14:08:04.921787+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "372df4da6a50"
down_revision: str | None = "fe4e5f71e14b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("maximo_assetnum", sa.String(), nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "maximo_assetnum", schema=schema)
    # ### end Alembic commands ###
