"""Add admin.company_projects

Revision ID: 0dca972dbdc5
Revises: ff56453fa9be
Create Date: 2024-10-22 21:28:10.950718+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dca972dbdc5"
down_revision: str | None = "ff56453fa9be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_projects",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("vector_store_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "project_id"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_projects", schema="admin")
    # ### end Alembic commands ###
