"""Add project devices, tags, and data tables

Revision ID: 98bacf75e0b3
Revises: 576e68812efc
Create Date: 2024-01-12 20:22:35.234161+00:00

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "98bacf75e0b3"
down_revision: str | None = "576e68812efc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("device_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("device_type_id", sa.Integer(), nullable=False),
        sa.Column("parent_device_id", sa.Integer(), nullable=True),
        sa.Column("logical", sa.Boolean(), nullable=False),
        sa.Column("name_short", sa.String(), nullable=True),
        sa.Column("name_long", sa.String(), nullable=True),
        sa.Column(
            "point",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "polygon",
            geoalchemy2.types.Geography(
                srid=4326,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["device_type_id"],
            ["operational.device_types.device_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_device_id"],
            [f"{schema}.devices.device_id"],
        ),
        sa.PrimaryKeyConstraint("device_id"),
        schema=schema,
    )
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("sensor_type_id", sa.Integer(), nullable=True),
        sa.Column("data_type_id", sa.SmallInteger(), nullable=True),
        sa.Column("name_short", sa.String(), nullable=True),
        sa.Column("name_long", sa.String(), nullable=True),
        sa.Column("name_scada", sa.String(), nullable=True),
        sa.Column("scada_id", sa.Integer(), nullable=True),
        sa.Column("scada_type", sa.String(), nullable=True),
        sa.Column("unit_scada", sa.String(), nullable=True),
        sa.Column("unit_offset", sa.Double(), nullable=True),
        sa.Column("unit_scale", sa.Double(), nullable=True),
        sa.Column(
            "point",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "polygon",
            geoalchemy2.types.Geography(
                srid=4326,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["data_type_id"],
            ["operational.data_types.data_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            [f"{schema}.devices.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sensor_type_id"],
            ["operational.sensor_types.sensor_type_id"],
        ),
        sa.PrimaryKeyConstraint("tag_id"),
        schema=schema,
    )
    op.create_table(
        "data",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("value_continuous", sa.Double(), nullable=True),
        sa.Column("value_boolean", sa.Boolean(), nullable=True),
        sa.Column("value_cumulative", sa.BigInteger(), nullable=True),
        sa.Column("value_string", sa.String(), nullable=True),
        sa.Column("value_status", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            [f"{schema}.tags.tag_id"],
        ),
        sa.PrimaryKeyConstraint("time", "tag_id"),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data", schema=schema)
    op.drop_table("tags", schema=schema)
    op.drop_table("devices", schema=schema)
    # ### end Alembic commands ###
