"""Add NOT NULL constraint to operational.failure_modes.device_type_id

Revision ID: 9185b67cf311
Revises: b38017adcb3c
Create Date: 2024-11-07 15:28:30.897216+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9185b67cf311"
down_revision: str | None = "b38017adcb3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "failure_modes",
        "device_type_id",
        existing_type=sa.SMALLINT(),
        nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "failure_modes",
        "device_type_id",
        existing_type=sa.SMALLINT(),
        nullable=True,
        schema="operational",
    )
    # ### end Alembic commands ###
