"""Add operational.pg_data_types table

Revision ID: 4fff41176534
Revises: 34cc402cd13f
Create Date: 2024-12-23 21:48:40.116232+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fff41176534"
down_revision: str | None = "34cc402cd13f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pg_data_types",
        sa.Column(
            "pg_data_type_id",
            sa.SmallInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("pg_data_type_id"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pg_data_types", schema="operational")
    # ### end Alembic commands ###
