"""Add expected_metrics and expected_metric_types to operational schema

Revision ID: 633b78a0f2c8
Revises: 25acbd263ca3
Create Date: 2024-12-10 22:14:20.019158+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "633b78a0f2c8"
down_revision: str | None = "25acbd263ca3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expected_metric_types",
        sa.Column(
            "expected_metric_type_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("expected_metric_type_id"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    op.create_table(
        "expected_metrics",
        sa.Column(
            "expected_metric_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("expected_metric_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "includes_soiling",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        sa.Column(
            "includes_warranted_degradation",
            sa.Boolean(),
            server_default="TRUE",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["expected_metric_type_id"],
            ["operational.expected_metric_types.expected_metric_type_id"],
        ),
        sa.PrimaryKeyConstraint("expected_metric_id"),
        sa.UniqueConstraint(
            "expected_metric_type_id",
            "includes_soiling",
            "includes_warranted_degradation",
            name="uq_expected_metric",
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expected_metrics", schema="operational")
    op.drop_table("expected_metric_types", schema="operational")
    # ### end Alembic commands ###
