"""Add operational.documents table

Revision ID: ff56453fa9be
Revises: ad7edf5ed267
Create Date: 2024-10-22 17:49:29.617919+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff56453fa9be"
down_revision: str | None = "ad7edf5ed267"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("openai_file_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("document_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents", schema="operational")
    # ### end Alembic commands ###
