"""Add device_type_id field to kpi_types table

Revision ID: 95e683a10b96
Revises: 1a5b150d871e
Create Date: 2024-09-05 16:54:42.323435+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95e683a10b96"
down_revision: str | None = "1a5b150d871e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kpi_types",
        sa.Column("device_type_id", sa.Integer(), nullable=True),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "kpi_types",
        "device_types",
        ["device_type_id"],
        ["device_type_id"],
        source_schema="operational",
        referent_schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "kpi_types", schema="operational", type_="foreignkey")
    op.drop_column("kpi_types", "device_type_id", schema="operational")
    # ### end Alembic commands ###
