"""Add dam_spp and rtm_spp tables

Revision ID: 07f1b4ccd632
Revises: 3ffeeeb8f7d6
Create Date: 2024-01-16 21:31:33.318134+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07f1b4ccd632"
down_revision: str | None = "3ffeeeb8f7d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dam_spp",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settlement_point_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["settlement_point_id"],
            ["ercot.settlement_points.settlement_point_id"],
        ),
        sa.PrimaryKeyConstraint("time", "settlement_point_id"),
        schema="ercot",
    )
    op.execute(
        """
        SELECT create_hypertable('ercot.dam_spp', 'time');
        """,
    )
    op.create_table(
        "rtm_spp",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settlement_point_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["settlement_point_id"],
            ["ercot.settlement_points.settlement_point_id"],
        ),
        sa.PrimaryKeyConstraint("time", "settlement_point_id"),
        schema="ercot",
    )
    op.execute(
        """
        SELECT create_hypertable('ercot.rtm_spp', 'time');
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rtm_spp", schema="project_default")
    op.drop_table("dam_spp", schema="project_default")
    # ### end Alembic commands ###
