"""Add pv_module_id to devices tables

Revision ID: f55a8b6463f1
Revises: a74670fe682d
Create Date: 2024-12-18 14:53:31.550587+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "f55a8b6463f1"
down_revision: str | None = "a74670fe682d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("pv_module_id", sa.Integer(), nullable=True),
        schema=schema,
    )
    op.create_foreign_key(
        None,
        "devices",
        "pv_modules",
        ["pv_module_id"],
        ["pv_module_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "devices", schema=schema, type_="foreignkey")
    op.drop_column("devices", "pv_module_id", schema=schema)
    # ### end Alembic commands ###
