"""Remove root_cause_id field from events tables

Revision ID: 4e0ef78fe236
Revises: 316369becf70
Create Date: 2024-05-14 21:49:46.800829+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e0ef78fe236"
down_revision: str | None = "316369becf70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "root_cause_id", schema=schema)
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "root_cause_id",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        schema=schema,
    )
    op.create_foreign_key(
        "events_root_cause_id_fkey",
        "events",
        "root_causes",
        ["root_cause_id"],
        ["root_cause_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    # ### end Alembic commands ###
