"""Add has_tracker_layout field to projects table

Revision ID: 1a5d0b6f51cd
Revises: 7a78dd7877ee
Create Date: 2024-03-07 01:35:08.300594+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a5d0b6f51cd"
down_revision: str | None = "7a78dd7877ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "has_tracker_layout",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "has_tracker_layout", schema="operational")
    # ### end Alembic commands ###
