"""Add projects table

Revision ID: 8cbc0333d8ec
Revises: 8c3bb646d04f
Create Date: 2024-01-12 19:23:35.166808+00:00

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cbc0333d8ec"
down_revision: str | None = "8c3bb646d04f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("project_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.Column("data_interval", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column(
            "point",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "polygon",
            geoalchemy2.types.Geography(
                srid=4326,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("time_zone", sa.String(), nullable=False),
        sa.Column("poi", sa.REAL(), nullable=False),
        sa.Column("capacity_dc", sa.REAL(), nullable=False),
        sa.Column("capacity_ac", sa.REAL(), nullable=False),
        sa.Column("duration", sa.REAL(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_type_id"],
            ["operational.project_types.project_type_id"],
        ),
        sa.PrimaryKeyConstraint("project_id"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects", schema="operational")
    # ### end Alembic commands ###
