"""Add capacity_ac field to devices tables

Revision ID: c63b15d249f9
Revises: 5f910ce1fe2d
Create Date: 2024-04-18 21:52:00.445473+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c63b15d249f9"
down_revision: str | None = "5f910ce1fe2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("capacity_ac", sa.REAL(), nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "capacity_ac", schema=schema)
    # ### end Alembic commands ###
