"""Add resources table

Revision ID: 06450205f6da
Revises: 4bc1330d21b8
Create Date: 2024-01-15 16:38:30.961839+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06450205f6da"
down_revision: str | None = "4bc1330d21b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources",
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("name_gen", sa.String(), nullable=False),
        sa.Column("name_load", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.Column("county", sa.String(), nullable=False),
        sa.Column("in_service", sa.SmallInteger(), nullable=False),
        sa.Column("capacity_power", sa.Double(), nullable=False),
        sa.Column("qse_id", sa.Integer(), nullable=False),
        sa.Column("dme_id", sa.Integer(), nullable=False),
        sa.Column("settlement_point_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dme_id"],
            ["ercot.dmes.dme_id"],
        ),
        sa.ForeignKeyConstraint(
            ["qse_id"],
            ["ercot.qses.qse_id"],
        ),
        sa.ForeignKeyConstraint(
            ["settlement_point_id"],
            ["ercot.settlement_points.settlement_point_id"],
        ),
        sa.PrimaryKeyConstraint("resource_id"),
        sa.UniqueConstraint("name_gen"),
        schema="ercot",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resources", schema="ercot")
    # ### end Alembic commands ###
