"""Add root_cause_id to events project tables

Revision ID: 7e7da20441c6
Revises: 9185b67cf311
Create Date: 2024-11-07 15:32:14.924195+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "7e7da20441c6"
down_revision: str | None = "9185b67cf311"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("root_cause_id", sa.Integer(), nullable=True),
        schema=schema,
    )
    op.create_foreign_key(
        None,
        "events",
        "root_causes",
        ["root_cause_id"],
        ["root_cause_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", schema=schema, type_="foreignkey")
    op.drop_column("events", "root_cause_id", schema=schema)
    # ### end Alembic commands ###
