"""Add remove existing event_losses table

Revision ID: 6024766fdcde
Revises: 5bdb213a2978
Create Date: 2024-05-21 15:30:37.609322+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "6024766fdcde"
down_revision: str | None = "5bdb213a2978"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("event_losses_time_idx", table_name="event_losses", schema=schema)
    op.drop_index("ix_event_id_time_desc", table_name="event_losses", schema=schema)
    op.drop_table("event_losses", schema=schema)
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_losses",
        sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "loss_energy",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "loss_financial",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "loss_availability",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            [f"{schema}.events.event_id"],
            name="event_losses_event_id_fkey",
        ),
        sa.PrimaryKeyConstraint("event_id", "time", name="event_losses_pkey"),
        schema=schema,
    )
    op.create_index(
        "ix_event_id_time_desc",
        "event_losses",
        ["event_id", sa.text("time DESC")],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "event_losses_time_idx",
        "event_losses",
        [sa.text("time DESC")],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###
