"""Add reports tables

Revision ID: 2047cf2664c5
Revises: efb5b1e1d9cc
Create Date: 2024-03-20 23:44:05.586649+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "2047cf2664c5"
down_revision: str | None = "efb5b1e1d9cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("report_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_generated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_pdf", postgresql.BYTEA(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_type_id"],
            ["operational.report_types.report_type_id"],
        ),
        sa.PrimaryKeyConstraint("report_type_id", "time"),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reports", schema=schema)
    # ### end Alembic commands ###
