"""Add ppa field to projects table

Revision ID: b2316d939a4a
Revises: 4b9d9ef76e17
Create Date: 2024-07-20 14:10:40.681721+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b2316d939a4a"
down_revision: str | None = "4b9d9ef76e17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("ppa", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "ppa", schema="operational")
    # ### end Alembic commands ###
