"""Add company_permissions table

Revision ID: f2e1a470dd89
Revises: 400855399764
Create Date: 2024-11-14 21:42:38.023539+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2e1a470dd89"
down_revision: str | None = "400855399764"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_permissions",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["admin.permissions.permission_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "permission_id", "project_id"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_permissions", schema="admin")
    # ### end Alembic commands ###
