"""Drop event_type_id from events tables

Revision ID: bb18a5148c50
Revises: 82f42ca7a88a
Create Date: 2024-11-07 16:59:07.972980+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb18a5148c50"
down_revision: str | None = "82f42ca7a88a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "events_event_type_id_device_id_time_start_key",
        "events",
        schema=schema,
        type_="unique",
    )
    op.drop_index("ix_project_events_event_type_id", table_name="events", schema=schema)
    op.create_unique_constraint(
        None,
        "events",
        ["device_id", "time_start"],
        schema=schema,
    )
    op.drop_constraint(
        "events_event_type_id_fkey",
        "events",
        schema=schema,
        type_="foreignkey",
    )
    op.drop_column("events", "event_type_id", schema=schema)
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("event_type_id", sa.SMALLINT(), autoincrement=False, nullable=True),
        schema=schema,
    )
    op.create_foreign_key(
        "events_event_type_id_fkey",
        "events",
        "event_types",
        ["event_type_id"],
        ["event_type_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    op.drop_constraint(None, "events", schema=schema, type_="unique")
    op.create_index(
        "ix_project_events_event_type_id",
        "events",
        ["event_type_id"],
        unique=False,
        schema=schema,
    )
    op.create_unique_constraint(
        "events_event_type_id_device_id_time_start_key",
        "events",
        ["event_type_id", "device_id", "time_start"],
        schema=schema,
    )
    # ### end Alembic commands ###
