"""Drop admin.user_permissions table

Revision ID: 400855399764
Revises: 25410bf19dee
Create Date: 2024-11-14 21:28:18.943170+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "400855399764"
down_revision: str | None = "25410bf19dee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_permissions", schema="admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_permissions",
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "operational_project_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operational_project_id"],
            ["operational.projects.project_id"],
            name="user_permissions_operational_project_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
            name="user_permissions_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "user_id",
            "operational_project_id",
            name="user_permissions_pkey",
        ),
        schema="admin",
    )
    # ### end Alembic commands ###
