"""Add CEC PV inverter and module tables

Revision ID: f9fbef4d6644
Revises: 376cea900e93
Create Date: 2024-08-05 17:56:17.215512+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9fbef4d6644"
down_revision: str | None = "376cea900e93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cec_pv_inverters",
        sa.Column("cec_pv_inverter_id", sa.Integer(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("model_number", sa.String(), nullable=False),
        sa.Column("hybrid_inverter", sa.Boolean(), nullable=True),
        sa.Column("ul1741sb_certification", sa.Boolean(), nullable=True),
        sa.Column("ul1741sa_testing", sa.Boolean(), nullable=True),
        sa.Column("ul1741sa_13_volt_var", sa.Boolean(), nullable=True),
        sa.Column("ul1741sa_freq_watt_volt_watt", sa.Boolean(), nullable=True),
        sa.Column("ul1741sa_disable_permit_service", sa.Boolean(), nullable=True),
        sa.Column("common_smart_inverter_profile", sa.Boolean(), nullable=True),
        sa.Column("monitor_key_data_scheduling", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("max_output_power_unity_pf", sa.Float(), nullable=True),
        sa.Column("nominal_voltage", sa.Float(), nullable=True),
        sa.Column("weighted_efficiency", sa.Float(), nullable=True),
        sa.Column("ul1741sb_certification_3rd_ed_entity", sa.String(), nullable=True),
        sa.Column("ul1741sb_certification_3rd_ed_date", sa.Date(), nullable=True),
        sa.Column("ul1741sa_certification_sa8_sa13_entity", sa.String(), nullable=True),
        sa.Column("ul1741sa_certification_sa8_sa13_date", sa.Date(), nullable=True),
        sa.Column(
            "ul1741sa_certification_sa8_sa13_firmware_versions",
            sa.String(),
            nullable=True,
        ),
        sa.Column("ul1741sa_13_volt_var_date", sa.Date(), nullable=True),
        sa.Column("ul1741sa_freq_watt_volt_watt_date", sa.Date(), nullable=True),
        sa.Column("ul1741sa_disable_permit_service_date", sa.Date(), nullable=True),
        sa.Column("inverter_csip_conformance_entity", sa.String(), nullable=True),
        sa.Column("inverter_csip_conformance_date", sa.Date(), nullable=True),
        sa.Column("monitor_key_data_scheduling_att", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("built_in_meter", sa.Boolean(), nullable=True),
        sa.Column("microinverter", sa.Boolean(), nullable=True),
        sa.Column("night_tare_loss", sa.Float(), nullable=True),
        sa.Column("power_rating_40_deg_c", sa.Float(), nullable=True),
        sa.Column("night_tare_loss_40_deg_c", sa.Float(), nullable=True),
        sa.Column("voltage_minimum", sa.Float(), nullable=True),
        sa.Column("voltage_nominal", sa.Float(), nullable=True),
        sa.Column("voltage_maximum", sa.Float(), nullable=True),
        sa.Column("power_level_10", sa.Float(), nullable=True),
        sa.Column("power_level_20", sa.Float(), nullable=True),
        sa.Column("power_level_30", sa.Float(), nullable=True),
        sa.Column("power_level_50", sa.Float(), nullable=True),
        sa.Column("power_level_75", sa.Float(), nullable=True),
        sa.Column("power_level_100", sa.Float(), nullable=True),
        sa.Column("efficiency_vmin_10", sa.Float(), nullable=True),
        sa.Column("efficiency_vmin_20", sa.Float(), nullable=True),
        sa.Column("efficiency_vmin_30", sa.Float(), nullable=True),
        sa.Column("efficiency_vmin_50", sa.Float(), nullable=True),
        sa.Column("efficiency_vmin_75", sa.Float(), nullable=True),
        sa.Column("efficiency_vmin_100", sa.Float(), nullable=True),
        sa.Column("efficiency_vmin_wtd", sa.Float(), nullable=True),
        sa.Column("efficiency_vnom_10", sa.Float(), nullable=True),
        sa.Column("efficiency_vnom_20", sa.Float(), nullable=True),
        sa.Column("efficiency_vnom_30", sa.Float(), nullable=True),
        sa.Column("efficiency_vnom_50", sa.Float(), nullable=True),
        sa.Column("efficiency_vnom_75", sa.Float(), nullable=True),
        sa.Column("efficiency_vnom_100", sa.Float(), nullable=True),
        sa.Column("efficiency_vnom_wtd", sa.Float(), nullable=True),
        sa.Column("efficiency_vmax_10", sa.Float(), nullable=True),
        sa.Column("efficiency_vmax_20", sa.Float(), nullable=True),
        sa.Column("efficiency_vmax_30", sa.Float(), nullable=True),
        sa.Column("efficiency_vmax_50", sa.Float(), nullable=True),
        sa.Column("efficiency_vmax_75", sa.Float(), nullable=True),
        sa.Column("efficiency_vmax_100", sa.Float(), nullable=True),
        sa.Column("efficiency_vmax_wtd", sa.Float(), nullable=True),
        sa.Column("grid_support_listing_date", sa.Date(), nullable=True),
        sa.Column("last_update", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("cec_pv_inverter_id"),
        sa.UniqueConstraint("manufacturer", "model_number"),
        schema="operational",
    )
    op.create_table(
        "cec_pv_modules",
        sa.Column("cec_pv_module_id", sa.Integer(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("model_number", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("safety_certification", sa.String(), nullable=True),
        sa.Column("nameplate_pmax", sa.Float(), nullable=True),
        sa.Column("ptc", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("design_qualification", sa.Date(), nullable=True),
        sa.Column("performance_evaluation", sa.String(), nullable=True),
        sa.Column("family", sa.String(), nullable=True),
        sa.Column("technology", sa.String(), nullable=True),
        sa.Column("a_c", sa.Float(), nullable=True),
        sa.Column("n_s", sa.Integer(), nullable=True),
        sa.Column("n_p", sa.Integer(), nullable=True),
        sa.Column("bipv", sa.Boolean(), nullable=True),
        sa.Column("nameplate_isc", sa.Float(), nullable=True),
        sa.Column("nameplate_voc", sa.Float(), nullable=True),
        sa.Column("nameplate_ipmax", sa.Float(), nullable=True),
        sa.Column("nameplate_vpmax", sa.Float(), nullable=True),
        sa.Column("average_noct", sa.Float(), nullable=True),
        sa.Column("gamma_pmax", sa.Float(), nullable=True),
        sa.Column("alpha_isc", sa.Float(), nullable=True),
        sa.Column("beta_voc", sa.Float(), nullable=True),
        sa.Column("alpha_ipmax", sa.Float(), nullable=True),
        sa.Column("beta_vpmax", sa.Float(), nullable=True),
        sa.Column("ipmax_low", sa.Float(), nullable=True),
        sa.Column("vpmax_low", sa.Float(), nullable=True),
        sa.Column("ipmax_noct", sa.Float(), nullable=True),
        sa.Column("vpmax_noct", sa.Float(), nullable=True),
        sa.Column("mounting", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("short_side", sa.Float(), nullable=True),
        sa.Column("long_side", sa.Float(), nullable=True),
        sa.Column("geometric_multiplier", sa.Float(), nullable=True),
        sa.Column("p2p_ref", sa.Float(), nullable=True),
        sa.Column("cec_listing_date", sa.Date(), nullable=True),
        sa.Column("last_update", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("cec_pv_module_id"),
        sa.UniqueConstraint("manufacturer", "model_number"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cec_pv_modules", schema="operational")
    op.drop_table("cec_pv_inverters", schema="operational")
    # ### end Alembic commands ###
