"""Drop event_losses when an event is deleted

Revision ID: 82f42ca7a88a
Revises: cbab302e4aaf
Create Date: 2024-11-07 16:53:52.531717+00:00

"""

from collections.abc import Sequence

from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "82f42ca7a88a"
down_revision: str | None = "cbab302e4aaf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "event_losses_event_id_fkey",
        "event_losses",
        schema=schema,
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "event_losses",
        "events",
        ["event_id"],
        ["event_id"],
        source_schema=schema,
        referent_schema=schema,
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "event_losses", schema=schema, type_="foreignkey")
    op.create_foreign_key(
        "event_losses_event_id_fkey",
        "event_losses",
        "events",
        ["event_id"],
        ["event_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    # ### end Alembic commands ###
