"""added fields to expected energy table

Revision ID: a74670fe682d
Revises: da6b28647342
Create Date: 2024-12-16 17:14:44.507016+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "a74670fe682d"
down_revision: str | None = "da6b28647342"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_expected",
        sa.Column("confidence_tier", sa.Integer(), nullable=True),
        schema=schema,
    )
    op.add_column(
        "data_expected",
        sa.Column("confidence_codes", sa.String(), nullable=True),
        schema=schema,
    )
    op.add_column(
        "data_expected",
        sa.Column("version", sa.String(), nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_expected", "version", schema=schema)
    op.drop_column("data_expected", "confidence_codes", schema=schema)
    op.drop_column("data_expected", "confidence_tier", schema=schema)
    # ### end Alembic commands ###
