"""Remove subscription columns from admin.users

Revision ID: b0f345eed72f
Revises: 61c9053b4162
Create Date: 2024-11-11 15:41:44.205226+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0f345eed72f"
down_revision: str | None = "61c9053b4162"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "subscribed_to_alerts", schema="admin")
    op.drop_column("users", "subscribed_to_reports", schema="admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "subscribed_to_reports",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        schema="admin",
    )
    op.add_column(
        "users",
        sa.Column(
            "subscribed_to_alerts",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        schema="admin",
    )
    # ### end Alembic commands ###
