"""Add new event_losses table

Revision ID: 561951348fb6
Revises: 6024766fdcde
Create Date: 2024-05-21 15:40:03.437557+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "561951348fb6"
down_revision: str | None = "6024766fdcde"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_losses",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_loss_type_id", sa.Integer(), nullable=False),
        sa.Column("loss", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            [f"{schema}.events.event_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_loss_type_id"],
            ["operational.event_loss_types.event_loss_type_id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "time", "event_loss_type_id"),
        schema=schema,
    )
    op.execute(
        f"""
        SELECT create_hypertable('{schema}.event_losses', 'time');
        """,
    )
    op.create_index(
        "ix_event_id_time_desc",
        "event_losses",
        ["event_id", sa.text("time DESC")],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_id_time_desc", table_name="event_losses", schema=schema)
    op.drop_table("event_losses", schema=schema)
    # ### end Alembic commands ###
