"""Add project pdf_reports table

Revision ID: 4bc36726a367
Revises: 14b4d9895cfa
Create Date: 2024-02-12 21:09:52.774254+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "4bc36726a367"
down_revision: str | None = "14b4d9895cfa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pdf_reports",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("data", postgresql.BYTEA(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pdf_reports", schema=schema)
    # ### end Alembic commands ###
