"""Add project events table

Revision ID: 50fb88344e68
Revises: 669a2584ae9e
Create Date: 2024-01-31 15:19:36.043599+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50fb88344e68"
down_revision: str | None = "669a2584ae9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("event_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("time_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_detected", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_last_analyzed", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            [f"{schema}.devices.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["operational.event_types.event_type_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("event_type_id", "device_id", "time_start"),
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_events_device_id"),
        "events",
        ["device_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_events_event_type_id"),
        "events",
        ["event_type_id"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f(f"ix_{schema}_events_event_type_id"),
        table_name="events",
        schema=schema,
    )
    op.drop_index(
        op.f(f"ix_{schema}_events_device_id"),
        table_name="events",
        schema=schema,
    )
    op.drop_table("events", schema=schema)
    # ### end Alembic commands ###
