"""Add rackings and racking_types tables

Revision ID: 808ca99ecda7
Revises: d9ca0728178c
Create Date: 2024-11-06 02:44:38.399559+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "808ca99ecda7"
down_revision: str | None = "d9ca0728178c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "racking_types",
        sa.Column(
            "racking_type_id",
            sa.SmallInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("racking_type_id"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    op.create_table(
        "rackings",
        sa.Column("racking_id", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("racking_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("max_rotation_angle", sa.Float(), nullable=False),
        sa.Column("min_rotation_angle", sa.Float(), nullable=False),
        sa.Column("wind_stow_angle", sa.Float(), nullable=False),
        sa.Column("wind_stow_threshold", sa.Float(), nullable=False),
        sa.Column("hail_stow_angle", sa.Float(), nullable=False),
        sa.Column("snow_stow_angle", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["racking_type_id"],
            ["operational.racking_types.racking_type_id"],
        ),
        sa.PrimaryKeyConstraint("racking_id"),
        sa.UniqueConstraint("model"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rackings", schema="operational")
    op.drop_table("racking_types", schema="operational")
    # ### end Alembic commands ###
