"""Add elevation column to operational.projects

Revision ID: 9ec1f065b1b4
Revises: 0dca972dbdc5
Create Date: 2024-10-30 19:47:22.472800+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ec1f065b1b4"
down_revision: str | None = "0dca972dbdc5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("elevation", sa.REAL(), server_default="0", nullable=False),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "elevation", schema="operational")
    # ### end Alembic commands ###
