"""Add event_losses tables

Revision ID: 235f6feda4a3
Revises: dfdbe1df97d7
Create Date: 2024-05-13 22:41:17.251601+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "235f6feda4a3"
down_revision: str | None = "dfdbe1df97d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_losses",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("loss_energy", sa.Double(), nullable=True),
        sa.Column("loss_financial", sa.Double(), nullable=True),
        sa.Column("loss_availability", sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            [f"{schema}.events.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "time"),
        schema=schema,
    )
    op.execute(
        f"""
        SELECT create_hypertable('{schema}.event_losses', 'time');
        """,
    )
    op.create_index(
        "ix_event_id_time_desc",
        "event_losses",
        ["event_id", sa.text("time DESC")],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_id_time_desc", table_name="event_losses", schema=schema)
    op.drop_table("event_losses", schema=schema)
    # ### end Alembic commands ###
