"""Add cec_pv_inverter_id and cec_pv_module_id to devices tables

Revision ID: c82038e0ae9b
Revises: f9fbef4d6644
Create Date: 2024-08-05 21:18:36.652691+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "c82038e0ae9b"
down_revision: str | None = "f9fbef4d6644"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("cec_pv_inverter_id", sa.Integer(), nullable=True),
        schema=schema,
    )
    op.add_column(
        "devices",
        sa.Column("cec_pv_module_id", sa.Integer(), nullable=True),
        schema=schema,
    )
    op.create_foreign_key(
        None,
        "devices",
        "cec_pv_inverters",
        ["cec_pv_inverter_id"],
        ["cec_pv_inverter_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    op.create_foreign_key(
        None,
        "devices",
        "cec_pv_modules",
        ["cec_pv_module_id"],
        ["cec_pv_module_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "devices_cec_pv_inverter_id_fkey",
        "devices",
        schema=schema,
        type_="foreignkey",
    )
    op.drop_constraint(
        "devices_cec_pv_module_id_fkey",
        "devices",
        schema=schema,
        type_="foreignkey",
    )
    op.drop_column("devices", "cec_pv_module_id", schema=schema)
    op.drop_column("devices", "cec_pv_inverter_id", schema=schema)
    # ### end Alembic commands ###
