"""Add NOT NULL constraint to pv_dc_combiners.modules_per_combiner table

Revision ID: d9ca0728178c
Revises: 417be9e9ecd4
Create Date: 2024-11-05 19:07:49.082283+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9ca0728178c"
down_revision: str | None = "417be9e9ecd4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pv_dc_combiners",
        "modules_per_combiner",
        existing_type=sa.SMALLINT(),
        nullable=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pv_dc_combiners",
        "modules_per_combiner",
        existing_type=sa.SMALLINT(),
        nullable=True,
        schema=schema,
    )
    # ### end Alembic commands ###
