"""Add sced_gen and sced_load table

Revision ID: 275f15769a30
Revises: 06450205f6da
Create Date: 2024-01-15 17:25:18.248703+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "275f15769a30"
down_revision: str | None = "06450205f6da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sced_load",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settlement_point_id", sa.Integer(), nullable=False),
        sa.Column("power_consumed", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["settlement_point_id"],
            ["ercot.settlement_points.settlement_point_id"],
        ),
        sa.PrimaryKeyConstraint("time", "settlement_point_id"),
        schema="ercot",
    )
    op.execute(
        """
        SELECT create_hypertable('ercot.sced_load', 'time');
        """,
    )
    op.create_table(
        "sced_gen",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("power_generated", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["ercot.resources.resource_id"],
        ),
        sa.PrimaryKeyConstraint("time", "resource_id"),
        schema="ercot",
    )
    op.execute(
        """
        SELECT create_hypertable('ercot.sced_gen', 'time');
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sced_gen", schema="ercot")
    op.drop_table("sced_load", schema="ercot")
    # ### end Alembic commands ###
