"""Add modules_per_pv_source_circuit to pv_dc_combiners table

Revision ID: bb54d9b2c547
Revises: 811913774182
Create Date: 2024-10-15 19:21:17.205312+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb54d9b2c547"
down_revision: str | None = "811913774182"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_dc_combiners",
        sa.Column("modules_per_pv_source_circuit", sa.SmallInteger(), nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_dc_combiners", "modules_per_pv_source_circuit", schema=schema)
    # ### end Alembic commands ###
