"""Add settlement_points table

Revision ID: 4bc1330d21b8
Revises: df2adc2e3874
Create Date: 2024-01-15 16:35:54.150315+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bc1330d21b8"
down_revision: str | None = "df2adc2e3874"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settlement_points",
        sa.Column("settlement_point_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("settlement_point_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("load_zone_id", sa.Integer(), nullable=True),
        sa.Column("trading_hub_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["load_zone_id"],
            ["ercot.settlement_points.settlement_point_id"],
        ),
        sa.ForeignKeyConstraint(
            ["settlement_point_type_id"],
            ["ercot.settlement_point_types.settlement_point_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["trading_hub_id"],
            ["ercot.settlement_points.settlement_point_id"],
        ),
        sa.PrimaryKeyConstraint("settlement_point_id"),
        sa.UniqueConstraint("name"),
        schema="ercot",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settlement_points", schema="ercot")
    # ### end Alembic commands ###
