"""Add image_url to projects table

Revision ID: b36ded8226ab
Revises: 21d387d77889
Create Date: 2024-10-02 13:58:59.747170+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b36ded8226ab"
down_revision: str | None = "21d387d77889"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("image_url", sa.String(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "image_url", schema="operational")
    # ### end Alembic commands ###
