"""Apply NOT NULL constraint to operational.projects.data_table

Revision ID: 34cc402cd13f
Revises: 4485eb3cb2f6
Create Date: 2024-12-23 18:21:56.860881+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34cc402cd13f"
down_revision: str | None = "4485eb3cb2f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "data_table",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "data_table",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="operational",
    )
    # ### end Alembic commands ###
