"""Add event_loss_types table

Revision ID: 5bdb213a2978
Revises: cd5be44a65ed
Create Date: 2024-05-20 22:47:17.345409+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bdb213a2978"
down_revision: str | None = "cd5be44a65ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_loss_types",
        sa.Column(
            "event_loss_type_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("event_loss_type_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_loss_types", schema="operational")
    # ### end Alembic commands ###
