"""Add has_event_integration and has_report_integration

Revision ID: 21d387d77889
Revises: e97e3ef7f016
Create Date: 2024-09-27 17:33:13.324572+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21d387d77889"
down_revision: str | None = "e97e3ef7f016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "has_event_integration",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column(
            "has_report_integration",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "has_report_integration", schema="operational")
    op.drop_column("projects", "has_event_integration", schema="operational")
    # ### end Alembic commands ###
