"""Add project kpi_data table

Revision ID: 1e1977fff740
Revises: c3b5581e3478
Create Date: 2024-01-24 23:08:22.826605+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "1e1977fff740"
down_revision: str | None = "c3b5581e3478"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_data",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kpi_type_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kpi_type_id"],
            ["operational.kpi_types.kpi_type_id"],
        ),
        sa.PrimaryKeyConstraint("time", "kpi_type_id"),
        schema=schema,
    )
    op.execute(
        f"""
        SELECT create_hypertable('{schema}.kpi_data', 'time');
        """,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kpi_data", schema=schema)
    # ### end Alembic commands ###
