"""add 2 dimension check constraint for db/models/inverter

Revision ID: 652e535cf2a6
Revises: f1a1331ea5d3
Create Date: 2025-07-29 21:47:08.819959+00:00

"""

from collections.abc import Sequence

from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "652e535cf2a6"
down_revision: str | None = "f1a1331ea5d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add 2-dimension check constraints for efficiency arrays in Inverter model
    op.create_check_constraint(
        "check_efficiency_at_low_voltage_ndims",
        "inverters",
        "array_ndims(efficiency_at_low_voltage) = 2",
        schema="operational",
    )

    op.create_check_constraint(
        "check_efficiency_at_mid_voltage_ndims",
        "inverters",
        "array_ndims(efficiency_at_mid_voltage) = 2",
        schema="operational",
    )

    op.create_check_constraint(
        "check_efficiency_at_high_voltage_ndims",
        "inverters",
        "array_ndims(efficiency_at_high_voltage) = 2",
        schema="operational",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop 2-dimension check constraints for efficiency arrays in Inverter model
    op.drop_constraint(
        "check_efficiency_at_high_voltage_ndims",
        "inverters",
        type_="check",
        schema="operational",
    )

    op.drop_constraint(
        "check_efficiency_at_mid_voltage_ndims",
        "inverters",
        type_="check",
        schema="operational",
    )

    op.drop_constraint(
        "check_efficiency_at_low_voltage_ndims",
        "inverters",
        type_="check",
        schema="operational",
    )
    # ### end Alembic commands ###
