"""Add data_cagg_interval to projects table

Revision ID: 21d52e20d562
Revises: 355e4d21c9a7
Create Date: 2025-02-03 18:48:18.309336+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21d52e20d562"
down_revision: str | None = "355e4d21c9a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("data_cagg_interval", sa.String(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "data_cagg_interval", schema="operational")
    # ### end Alembic commands ###
