"""Add contracts and contract_kpis tables

Revision ID: 955c9e25a4ee
Revises: f0b8ec32ee95
Create Date: 2025-01-27 23:16:03.115905+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "955c9e25a4ee"
down_revision: str | None = "f0b8ec32ee95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("contract_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("company_id_provider", sa.UUID(), nullable=False),
        sa.Column("company_id_counter", sa.UUID(), nullable=False),
        sa.Column("execution_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id_counter"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id_provider"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["operational.documents.document_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("contract_id"),
        sa.UniqueConstraint("document_id"),
        schema="operational",
    )
    op.create_table(
        "contract_kpis",
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("kpi_type_id", sa.Integer(), nullable=False),
        sa.Column("threshold", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "liquidated_damages",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "claim_howto",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("provider_responsible", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["operational.contracts.contract_id"],
        ),
        sa.ForeignKeyConstraint(
            ["kpi_type_id"],
            ["operational.kpi_types.kpi_type_id"],
        ),
        sa.PrimaryKeyConstraint("contract_id", "kpi_type_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contract_kpis", schema="operational")
    op.drop_table("contracts", schema="operational")
    # ### end Alembic commands ###
