"""project data interval enum

Revision ID: 3c815c918ee5
Revises: 6f8b6ee68711
Create Date: 2025-09-26 19:17:46.348745+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c815c918ee5"
down_revision: str | None = "6f8b6ee68711"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "data_interval",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("mqtt", "1sec", "1min", "5min", name="projectdatainterval"),
        existing_nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "data_interval",
        existing_type=sa.Enum(
            "mqtt", "1sec", "1min", "5min", name="projectdatainterval"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###
