"""add a shared pages table under admin

Revision ID: a3d4880fbab8
Revises: ccf8d74fa1fd
Create Date: 2025-09-15 18:45:59.548685+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3d4880fbab8"
down_revision: str | None = "ccf8d74fa1fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shared_pages",
        sa.Column("page_id", sa.UUID(), nullable=False),
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("page_slug", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("page_id"),
        sa.UniqueConstraint("page_slug"),
        sa.UniqueConstraint("page_url"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shared_pages", schema="admin")
    # ### end Alembic commands ###
