"""Add device_type_id to sensor_types

Revision ID: aead980be11e
Revises: a3d4880fbab8
Create Date: 2025-09-16 22:52:49.138584+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aead980be11e"
down_revision: str | None = "a3d4880fbab8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sensor_types",
        sa.Column("device_type_id", sa.Integer(), nullable=True),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "sensor_types",
        "device_types",
        ["device_type_id"],
        ["device_type_id"],
        source_schema="operational",
        referent_schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sensor_types", schema="operational", type_="foreignkey")
    op.drop_column("sensor_types", "device_type_id", schema="operational")
    # ### end Alembic commands ###
