"""Add device_type_id to devices tables

Revision ID: ab0aa5131b88
Revises: 756c4cb51823
Create Date: 2025-10-03 04:08:57.841049+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab0aa5131b88"
down_revision: str | None = "756c4cb51823"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("device_model_id", sa.Integer(), nullable=True),
        schema=schema,
    )
    op.create_foreign_key(
        None,
        "devices",
        "device_models",
        ["device_model_id"],
        ["device_model_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "devices", schema=schema, type_="foreignkey")
    op.drop_column("devices", "device_model_id", schema=schema)
    # ### end Alembic commands ###
