"""add event tables for refactor

Revision ID: 322768519682
Revises: 6f8b6ee68711
Create Date: 2025-09-29 14:17:06.457907+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "322768519682"
down_revision: str | None = "6f8b6ee68711"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events_2",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("failure_mode_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("root_cause_id", sa.Integer(), nullable=True),
        sa.Column("time_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_detected", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_last_analyzed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("loss_total_financial", sa.Double(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            [f"{schema}.devices.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["operational.failure_modes.failure_mode_id"],
        ),
        sa.ForeignKeyConstraint(
            ["root_cause_id"],
            ["operational.root_causes.root_cause_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("device_id", "time_start"),
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_events_2_device_id"),
        "events_2",
        ["device_id"],
        unique=False,
        schema=schema,
    )
    op.create_table(
        "event_losses_2",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_loss_type_id", sa.Integer(), nullable=False),
        sa.Column("loss", sa.Double(), nullable=False),
        sa.Column("version", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"], [f"{schema}.events_2.event_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["event_loss_type_id"],
            ["operational.event_loss_types.event_loss_type_id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "time", "event_loss_type_id"),
        schema=schema,
    )
    op.execute(
        f"SELECT create_hypertable('{schema}.event_losses_2', by_range('time'));",
    )
    op.create_index(
        "ix_event_id_time_desc_2",
        "event_losses_2",
        ["event_id", sa.literal_column("time DESC")],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_id_time_desc_2", table_name="event_losses_2", schema=schema)
    op.drop_table("event_losses_2", schema=schema)
    op.drop_index(
        op.f(f"ix_{schema}_events_2_device_id"),
        table_name="events_2",
        schema=schema,
    )
    op.drop_table("events_2", schema=schema)
    # ### end Alembic commands ###
