"""add user_kpi_type table to admin so that users can favorite kpis

Revision ID: 4befd61dc511
Revises: 798ad2a9a99d
Create Date: 2025-09-03 17:47:45.617375+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4befd61dc511"
down_revision: str | None = "798ad2a9a99d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_kpi_types",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("kpi_type_id", sa.Integer(), nullable=False),
        sa.Column("is_favorited", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["kpi_type_id"],
            ["operational.kpi_types.kpi_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "kpi_type_id"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_kpi_types", schema="admin")
    # ### end Alembic commands ###
