"""Drone integration

Revision ID: f77b0a9cea04
Revises: edb51ae438cb
Create Date: 2025-07-23 20:30:55.140843+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f77b0a9cea04"
down_revision: str | None = "edb51ae438cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drone_providers",
        sa.Column(
            "drone_provider_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("drone_provider_id"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    op.create_table(
        "drone_integrations",
        sa.Column(
            "drone_integration_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("drone_provider_id", sa.Integer(), nullable=False),
        sa.Column("provider_project_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drone_provider_id"],
            ["operational.drone_providers.drone_provider_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("drone_integration_id"),
        schema="operational",
    )
    op.create_table(
        "drone_permissions",
        sa.Column("drone_integration_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("can_view", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["drone_integration_id"],
            ["operational.drone_integrations.drone_integration_id"],
        ),
        sa.PrimaryKeyConstraint("drone_integration_id", "company_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drone_permissions", schema="operational")
    op.drop_table("drone_integrations", schema="operational")
    op.drop_table("drone_providers", schema="operational")
    # ### end Alembic commands ###
