"""Add data_timeseries tables

Revision ID: e6fe6ee493d8
Revises: 97c331e0c1f8
Create Date: 2025-01-08 20:37:04.343335+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6fe6ee493d8"
down_revision: str | None = "97c331e0c1f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_timeseries",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("value_integer", sa.Integer(), nullable=True),
        sa.Column("value_bigint", sa.BigInteger(), nullable=True),
        sa.Column("value_real", sa.REAL(), nullable=True),
        sa.Column("value_double", sa.Double(), nullable=True),
        sa.Column("value_boolean", sa.Boolean(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            [f"{schema}.tags.tag_id"],
        ),
        sa.PrimaryKeyConstraint("time", "tag_id"),
        schema=schema,
    )
    op.create_index(
        "data_timeseries_tag_id_time_idx",
        "data_timeseries",
        ["tag_id", sa.text("time DESC")],
        unique=False,
        schema=schema,
    )
    op.execute(
        f"""
        SELECT create_hypertable(
            '{schema}.data_timeseries',
            by_range('time', INTERVAL '12 hours')
        );
        """,
    )
    op.execute(
        f"""
        ALTER TABLE {schema}.data_timeseries
        SET (
            timescaledb.compress,
            timescaledb.compress_segmentby='tag_id'
        );
        """,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "data_timeseries_tag_id_time_idx",
        table_name="data_timeseries",
        schema=schema,
    )
    op.drop_table("data_timeseries", schema=schema)
    # ### end Alembic commands ###
