"""adding project info columns to project table

Revision ID: dac16b61358b
Revises: 4befd61dc511
Create Date: 2025-09-07 14:34:22.036311+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dac16b61358b"
down_revision: str | None = "4befd61dc511"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("commencement_of_construction_date", sa.Date(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("financial_close_date", sa.Date(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("notice_to_proceed_date", sa.Date(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("mechanical_completion_date", sa.Date(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("substantial_completion_date", sa.Date(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("interconnection_approval_date", sa.Date(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("performance_test_completion_date", sa.Date(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("placed_in_service_date", sa.Date(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("first_realtime_data_received_date", sa.Date(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("first_data_backfilled_date", sa.Date(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("interconnecting_iso", sa.String(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("interconnecting_utility", sa.String(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("interconnecting_node_code", sa.String(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("interconnecting_substation", sa.String(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("interconnecting_voltage", sa.REAL(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "interconnecting_voltage", schema="operational")
    op.drop_column("projects", "interconnecting_substation", schema="operational")
    op.drop_column("projects", "interconnecting_node_code", schema="operational")
    op.drop_column("projects", "interconnecting_utility", schema="operational")
    op.drop_column("projects", "interconnecting_iso", schema="operational")
    op.drop_column("projects", "first_data_backfilled_date", schema="operational")
    op.drop_column(
        "projects", "first_realtime_data_received_date", schema="operational"
    )
    op.drop_column("projects", "placed_in_service_date", schema="operational")
    op.drop_column("projects", "performance_test_completion_date", schema="operational")
    op.drop_column("projects", "interconnection_approval_date", schema="operational")
    op.drop_column("projects", "substantial_completion_date", schema="operational")
    op.drop_column("projects", "mechanical_completion_date", schema="operational")
    op.drop_column("projects", "notice_to_proceed_date", schema="operational")
    op.drop_column("projects", "financial_close_date", schema="operational")
    op.drop_column(
        "projects", "commencement_of_construction_date", schema="operational"
    )
    # ### end Alembic commands ###
