"""Add has_bess_banks and has_bess_strings to projects table

Revision ID: 355e4d21c9a7
Revises: 955c9e25a4ee
Create Date: 2025-01-29 14:54:23.324654+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "355e4d21c9a7"
down_revision: str | None = "955c9e25a4ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "has_bess_banks",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column(
            "has_bess_strings",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "has_bess_strings", schema="operational")
    op.drop_column("projects", "has_bess_banks", schema="operational")
    # ### end Alembic commands ###
