"""Add project_name and domain_name fields to operational.cmms_integrations table

Revision ID: f837939179f8
Revises: 64dde206babc
Create Date: 2025-04-21 23:05:28.688725+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f837939179f8"
down_revision: str | None = "64dde206babc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cmms_integrations",
        sa.Column("project_name", sa.String(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "cmms_integrations",
        sa.Column("domain_name", sa.String(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cmms_integrations", "domain_name", schema="operational")
    op.drop_column("cmms_integrations", "project_name", schema="operational")
    # ### end Alembic commands ###
