"""PRO-641 Add om_contractor_scopes table

Revision ID: 0f33e0e79766
Revises: b852ba8a78cd
Create Date: 2025-09-23 13:46:43.442722+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0f33e0e79766"
down_revision: str | None = "b852ba8a78cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "om_contractor_scopes",
        sa.Column(
            "om_contractor_scope_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "scope_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"device_type_ids": []}',
            nullable=False,
        ),
        sa.Column("contractor_addressee", sa.String(), nullable=True),
        sa.Column("contractor_email", sa.String(), nullable=True),
        sa.Column("contractor_phone", sa.String(), nullable=True),
        sa.CheckConstraint(
            "contractor_phone IS NULL OR contractor_phone ~ '^\\+?[1-9][0-9]{1,14}$'",
            name="chk_om_contractor_phone_e164",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("om_contractor_scope_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("om_contractor_scopes", schema="operational")
    # ### end Alembic commands ###
