"""Make projects.project_status_type_id not null and add default

Revision ID: 82d3bb3ce304
Revises: 9df16524cc6e
Create Date: 2025-08-01 21:28:09.199384+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from src.core import enumerations

# revision identifiers, used by Alembic.
revision: str = "82d3bb3ce304"
down_revision: str | None = "9df16524cc6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "project_status_type_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        server_default=str(enumerations.ProjectStatusType.ONBOARDING),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "project_status_type_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        server_default=None,
        schema="operational",
    )
    # ### end Alembic commands ###
