"""Add PV budgeted tables in operational schema

Revision ID: 756c4cb51823
Revises: 322768519682
Create Date: 2025-10-02 15:40:23.377262+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "756c4cb51823"
down_revision: str | None = "322768519682"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pv_budgeted_series",
        sa.Column(
            "pv_budgeted_series_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "p_value", sa.String(), nullable=False, comment="P-value (e.g., p50, p90)"
        ),
        sa.Column(
            "frequency",
            sa.String(),
            nullable=False,
            comment="Data frequency (e.g., hourly)",
        ),
        sa.Column(
            "soiling_mode",
            sa.Enum("FIXED", "PER_TIMESTAMP", name="pvbudgetedsoilingmode"),
            nullable=True,
            comment="Soiling calculation mode",
        ),
        sa.Column(
            "soiling_fixed_percentage",
            sa.Float(),
            nullable=True,
            comment="Fixed soiling percentage when mode is fixed",
        ),
        sa.Column(
            "tmy_source",
            sa.String(),
            nullable=True,
            comment="TMY data source (e.g., TMY NSRDB 2020)",
        ),
        sa.Column(
            "model_version",
            sa.String(),
            nullable=True,
            comment="PV model version (e.g., PVSyst 7.4.7)",
        ),
        sa.Column(
            "filename",
            sa.String(),
            nullable=True,
            comment="Source filename (e.g., DBD_VDU_res0.xlsx)",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("pv_budgeted_series_id"),
        schema="operational",
    )
    op.create_index(
        op.f("ix_operational_pv_budgeted_series_company_id"),
        "pv_budgeted_series",
        ["company_id"],
        unique=False,
        schema="operational",
    )
    op.create_index(
        op.f("ix_operational_pv_budgeted_series_project_id"),
        "pv_budgeted_series",
        ["project_id"],
        unique=False,
        schema="operational",
    )
    op.create_table(
        "pv_budgeted_data",
        sa.Column("pv_budgeted_series_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "poi_ac_power",
            sa.Float(),
            nullable=False,
            comment="Point of Interconnection AC Power [MW]",
        ),
        sa.Column(
            "ghi",
            sa.Float(),
            nullable=False,
            comment="Global Horizontal Irradiance [W/m²]",
        ),
        sa.Column(
            "poa",
            sa.Float(),
            nullable=False,
            comment="Plane of Array Irradiance [W/m²]",
        ),
        sa.Column(
            "temperature", sa.Float(), nullable=False, comment="Temperature [°C]"
        ),
        sa.Column(
            "soiling_percentage",
            sa.Float(),
            nullable=False,
            comment="Soiling loss as percentage [%]",
        ),
        sa.ForeignKeyConstraint(
            ["pv_budgeted_series_id"],
            ["operational.pv_budgeted_series.pv_budgeted_series_id"],
        ),
        sa.PrimaryKeyConstraint("pv_budgeted_series_id", "time"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pv_budgeted_data", schema="operational")
    op.drop_index(
        op.f("ix_operational_pv_budgeted_series_project_id"),
        table_name="pv_budgeted_series",
        schema="operational",
    )
    op.drop_index(
        op.f("ix_operational_pv_budgeted_series_company_id"),
        table_name="pv_budgeted_series",
        schema="operational",
    )
    op.drop_table("pv_budgeted_series", schema="operational")
    # ### end Alembic commands ###
