"""Add operational.report_instances

Revision ID: 701410c6d940
Revises: 234e0a7e2316
Create Date: 2025-01-27 17:54:46.535568+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "701410c6d940"
down_revision: str | None = "234e0a7e2316"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_instances",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("report_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_type_id"],
            ["operational.report_types.report_type_id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "report_type_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report_instances", schema="operational")
    # ### end Alembic commands ###
