"""adding company_id as a part of the unique constraints for pv equipment

Revision ID: ff69879136a5
Revises: a0f3bd16b031
Create Date: 2025-05-28 17:09:31.335344+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff69879136a5"
down_revision: str | None = "a0f3bd16b031"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "inverters_manufacturer_model_key",
        "inverters",
        schema="operational",
        type_="unique",
    )
    op.create_unique_constraint(
        None,
        "inverters",
        ["manufacturer", "model", "company_id"],
        schema="operational",
    )
    op.drop_constraint(
        "pv_modules_manufacturer_model_key",
        "pv_modules",
        schema="operational",
        type_="unique",
    )
    op.create_unique_constraint(
        None,
        "pv_modules",
        ["manufacturer", "model", "company_id"],
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pv_modules", schema="operational", type_="unique")
    op.create_unique_constraint(
        "pv_modules_manufacturer_model_key",
        "pv_modules",
        ["manufacturer", "model"],
        schema="operational",
    )
    op.drop_constraint(None, "inverters", schema="operational", type_="unique")
    op.create_unique_constraint(
        "inverters_manufacturer_model_key",
        "inverters",
        ["manufacturer", "model"],
        schema="operational",
    )
    # ### end Alembic commands ###
