"""add transformer

Revision ID: a31565d47392
Revises: 1d8e42ad80c6
Create Date: 2025-02-12 00:44:56.372277+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a31565d47392"
down_revision: str | None = "1d8e42ad80c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transformers",
        sa.Column("transformer_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("no_load_loss", sa.Float(), nullable=False),
        sa.Column("load_loss", sa.Float(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("transformer_id"),
        sa.UniqueConstraint("manufacturer", "model"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transformers", schema="operational")
    # ### end Alembic commands ###
