"""Add device_id_path to devices tables

Revision ID: 4fab95f099bb
Revises: 21d52e20d562
Create Date: 2025-02-06 17:43:54.056393+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from _alembic_migrations.tenant import for_each_project_schema

# revision identifiers, used by Alembic.
revision: str = "4fab95f099bb"
down_revision: str | None = "21d52e20d562"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("device_id_path", sa.String(), nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "device_id_path", schema=schema)
    # ### end Alembic commands ###
