"""add 2P racking columns

Revision ID: 634b4d867757
Revises: 2545dff31fd2
Create Date: 2025-07-04 00:40:05.803518+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "634b4d867757"
down_revision: str | None = "2545dff31fd2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rackings",
        sa.Column(
            "module_orientation",
            sa.SmallInteger(),
            server_default="1",
            nullable=False,
            comment="Orientation of module on the rack, either portrait or landscape",
        ),
        schema="operational",
    )
    op.add_column(
        "rackings",
        sa.Column(
            "num_modules_in_orientation",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="Number of modules in the given orientation",
        ),
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "max_rotation_angle",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Degrees",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "min_rotation_angle",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Degrees",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "wind_stow_angle",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Degrees",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "wind_stow_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Meters per Second",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "hail_stow_angle",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Degrees",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "snow_stow_angle",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Degrees",
        existing_nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rackings",
        "snow_stow_angle",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Degrees",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "hail_stow_angle",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Degrees",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "wind_stow_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Meters per Second",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "wind_stow_angle",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Degrees",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "min_rotation_angle",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Degrees",
        existing_nullable=False,
        schema="operational",
    )
    op.alter_column(
        "rackings",
        "max_rotation_angle",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Degrees",
        existing_nullable=False,
        schema="operational",
    )
    op.drop_column("rackings", "num_modules_in_orientation", schema="operational")
    op.drop_column("rackings", "module_orientation", schema="operational")
    # ### end Alembic commands ###
