"""add three columns to operational.projects

Revision ID: 61bf8f42726f
Revises: aa1c45369908
Create Date: 2025-06-16 22:59:46.151320+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61bf8f42726f"
down_revision: str | None = "aa1c45369908"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("last_updated_by", sa.String(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects", sa.Column("owner", sa.UUID(), nullable=True), schema="operational"
    )
    op.create_foreign_key(
        None,
        "projects",
        "users",
        ["last_updated_by"],
        ["user_id"],
        source_schema="operational",
        referent_schema="admin",
    )
    op.create_foreign_key(
        None,
        "projects",
        "companies",
        ["owner"],
        ["company_id"],
        source_schema="operational",
        referent_schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", schema="operational", type_="foreignkey")
    op.drop_constraint(None, "projects", schema="operational", type_="foreignkey")
    op.drop_column("projects", "owner", schema="operational")
    op.drop_column("projects", "last_updated_by", schema="operational")
    op.drop_column("projects", "last_updated", schema="operational")
    # ### end Alembic commands ###
