"""Add status_lookup_id to project tags tables

Revision ID: 83441f9639f5
Revises: 06705be5937a
Create Date: 2025-02-18 17:29:05.788913+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83441f9639f5"
down_revision: str | None = "06705be5937a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tags",
        sa.Column("status_lookup_id", sa.Integer(), nullable=True),
        schema=schema,
    )
    op.create_foreign_key(
        None,
        "tags",
        "status_lookup",
        ["status_lookup_id"],
        ["status_lookup_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", schema=schema, type_="foreignkey")
    op.drop_column("tags", "status_lookup_id", schema=schema)
    # ### end Alembic commands ###
