"""add company secrets table to admin

Revision ID: ccf8d74fa1fd
Revises: dac16b61358b
Create Date: 2025-09-10 23:11:25.825972+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccf8d74fa1fd"
down_revision: str | None = "dac16b61358b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_secrets",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("dtn_secret_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.PrimaryKeyConstraint("company_id"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_secrets", schema="admin")
    # ### end Alembic commands ###
