"""Add device_model_id to inverters, pv_modules, and rackings tables

Revision ID: 0847dc2d8a65
Revises: 159ebb4a0c6e
Create Date: 2025-12-27 03:53:57.025980+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0847dc2d8a65"
down_revision: str | None = "159ebb4a0c6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inverters",
        sa.Column("device_model_id", sa.Integer(), nullable=True),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "inverters",
        "device_models",
        ["device_model_id"],
        ["device_model_id"],
        source_schema="operational",
        referent_schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("device_model_id", sa.Integer(), nullable=True),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "pv_modules",
        "device_models",
        ["device_model_id"],
        ["device_model_id"],
        source_schema="operational",
        referent_schema="operational",
    )
    op.add_column(
        "rackings",
        sa.Column("device_model_id", sa.Integer(), nullable=True),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "rackings",
        "device_models",
        ["device_model_id"],
        ["device_model_id"],
        source_schema="operational",
        referent_schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rackings", schema="operational", type_="foreignkey")
    op.drop_column("rackings", "device_model_id", schema="operational")
    op.drop_constraint(None, "pv_modules", schema="operational", type_="foreignkey")
    op.drop_column("pv_modules", "device_model_id", schema="operational")
    op.drop_constraint(None, "inverters", schema="operational", type_="foreignkey")
    op.drop_column("inverters", "device_model_id", schema="operational")
    # ### end Alembic commands ###
