"""one more inverter column

Revision ID: f0b8ec32ee95
Revises: 701410c6d940
Create Date: 2025-01-27 18:59:58.127670+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0b8ec32ee95"
down_revision: str | None = "701410c6d940"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inverters",
        sa.Column("power_start_up", sa.Float(), nullable=False),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inverters", "power_start_up", schema="operational")
    # ### end Alembic commands ###
