"""Drop operational.projects.vector_store_id

Revision ID: 7a8247ac4cf4
Revises: 634b4d867757
Create Date: 2025-07-10 14:10:34.690445+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a8247ac4cf4"
down_revision: str | None = "634b4d867757"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "vector_store_id", schema="operational")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("vector_store_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###
