"""add is_commissioning column to operational.projects

Revision ID: 21ea67400d81
Revises: 29d69706c5f5
Create Date: 2025-06-10 21:50:26.480226+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21ea67400d81"
down_revision: str | None = "29d69706c5f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "is_commissioning", sa.Boolean(), server_default="TRUE", nullable=False
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_commissioning", schema="operational")
    # ### end Alembic commands ###
