"""Add status tables

Revision ID: 06705be5937a
Revises: a31565d47392
Create Date: 2025-02-18 17:26:17.405080+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06705be5937a"
down_revision: str | None = "a31565d47392"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "status_lookup",
        sa.Column(
            "status_lookup_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.Column("status_binary_id", sa.Integer(), nullable=True),
        sa.Column("status_string_id", sa.Integer(), nullable=True),
        sa.Column("status_boolean_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("status_lookup_id"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    op.create_table(
        "status_binary",
        sa.Column(
            "status_binary_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("bit_position", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("state_false", sa.String(), nullable=True),
        sa.Column("state_true", sa.String(), nullable=True),
        sa.Column("failure_mode_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["operational.failure_modes.failure_mode_id"],
        ),
        sa.PrimaryKeyConstraint("status_binary_id", "bit_position"),
        schema="operational",
    )
    op.create_table(
        "status_boolean",
        sa.Column(
            "status_boolean_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("state_false", sa.String(), nullable=True),
        sa.Column("state_true", sa.String(), nullable=False),
        sa.Column("failure_mode_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["operational.failure_modes.failure_mode_id"],
        ),
        sa.PrimaryKeyConstraint("status_boolean_id"),
        schema="operational",
    )
    op.create_table(
        "status_string",
        sa.Column(
            "status_string_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("string_trigger", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("failure_mode_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["operational.failure_modes.failure_mode_id"],
        ),
        sa.PrimaryKeyConstraint("status_string_id", "string_trigger"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status_string", schema="operational")
    op.drop_table("status_boolean", schema="operational")
    op.drop_table("status_binary", schema="operational")
    op.drop_table("status_lookup", schema="operational")
    # ### end Alembic commands ###
