"""add is_favorited to user_project table

Revision ID: ba5473e303cd
Revises: c82d6ac92e51
Create Date: 2025-08-06 19:31:22.462695+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba5473e303cd"
down_revision: str | None = "c82d6ac92e51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_projects",
        sa.Column("is_favorited", sa.Boolean(), server_default="false", nullable=False),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_projects", "is_favorited", schema="admin")
    # ### end Alembic commands ###
