"""add calendar item assignments

Revision ID: 0dd18a93ef5e
Revises: 4cc65ca91b27
Create Date: 2025-08-08 03:13:23.881596+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dd18a93ef5e"
down_revision: str | None = "4cc65ca91b27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_item_assignments",
        sa.Column(
            "assignment_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("calendar_item_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(user_id IS NOT NULL) <> (team_id IS NOT NULL)",
            name="chk_calendar_item_assignment_exactly_one_assignee",
        ),
        sa.ForeignKeyConstraint(
            ["calendar_item_id"],
            ["operational.calendar_items.calendar_item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["admin.teams.team_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("assignment_id"),
        schema="operational",
    )
    op.create_index(
        "ix_calendar_item_team_assignment_unique",
        "calendar_item_assignments",
        ["calendar_item_id", "team_id"],
        unique=True,
        schema="operational",
        postgresql_where=sa.text("team_id IS NOT NULL"),
    )
    op.create_index(
        "ix_calendar_item_user_assignment_unique",
        "calendar_item_assignments",
        ["calendar_item_id", "user_id"],
        unique=True,
        schema="operational",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_operational_calendar_item_assignments_calendar_item_id"),
        "calendar_item_assignments",
        ["calendar_item_id"],
        unique=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_operational_calendar_item_assignments_calendar_item_id"),
        table_name="calendar_item_assignments",
        schema="operational",
    )
    op.drop_index(
        "ix_calendar_item_user_assignment_unique",
        table_name="calendar_item_assignments",
        schema="operational",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_calendar_item_team_assignment_unique",
        table_name="calendar_item_assignments",
        schema="operational",
        postgresql_where=sa.text("team_id IS NOT NULL"),
    )
    op.drop_table("calendar_item_assignments", schema="operational")
    # ### end Alembic commands ###
