"""add custom dash tables

Revision ID: 8c0b7607756a
Revises: 9c1b8c1d5c93
Create Date: 2025-09-19 18:22:10.853408+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8c0b7607756a"
down_revision: str | None = "9c1b8c1d5c93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_dashboard_components",
        sa.Column("component_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("component_type", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("component_id"),
        schema="operational",
    )
    op.create_table(
        "custom_dashboards",
        sa.Column("dashboard_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("dashboard_name", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("default_time_range", sa.Integer(), nullable=False),
        sa.Column("default_kpi_time_range", sa.Integer(), nullable=False),
        sa.Column(
            "components", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["admin.users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("dashboard_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("custom_dashboards", schema="operational")
    op.drop_table("custom_dashboard_components", schema="operational")
    # ### end Alembic commands ###
