"""Add cmms_tickets to devices table

Revision ID: 9c1b8c1d5c93
Revises: ab1f8e762d0e
Create Date: 2025-09-19 18:11:51.351109+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9c1b8c1d5c93"
down_revision: str | None = "ab1f8e762d0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cmms_tickets",
        sa.Column("cmms_ticket_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cmms_integration_id", sa.Integer(), nullable=False),
        sa.Column(
            "db_created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "db_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("summary_long", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("status_change_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("priority", sa.String(), nullable=True),
        sa.Column("reporter", sa.String(), nullable=True),
        sa.Column("assigned_to", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("cmms_device_id", sa.String(), nullable=True),
        sa.Column("cmms_device_name", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("json_raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["cmms_integration_id"],
            ["operational.cmms_integrations.cmms_integration_id"],
        ),
        sa.PrimaryKeyConstraint("cmms_ticket_id"),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cmms_tickets", schema=schema)
    # ### end Alembic commands ###
