"""Add BESS capacity columns to projects table

Revision ID: 4df5b77373f4
Revises: 7b9764436f96
Create Date: 2025-03-06 16:11:13.964543+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4df5b77373f4"
down_revision: str | None = "7b9764436f96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("capacity_bess_power_ac", sa.REAL(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "projects",
        sa.Column("capacity_bess_energy_bol_dc", sa.REAL(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "capacity_bess_energy_bol_dc", schema="operational")
    op.drop_column("projects", "capacity_bess_power_ac", schema="operational")
    # ### end Alembic commands ###
