"""Add include_by_default to device_types

Revision ID: e68b7e364b0b
Revises: 9427f6331493
Create Date: 2025-03-04 18:19:11.071225+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e68b7e364b0b"
down_revision: str | None = "9427f6331493"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device_types",
        sa.Column(
            "include_by_default",
            sa.Boolean(),
            server_default="TRUE",
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device_types", "include_by_default", schema="operational")
    # ### end Alembic commands ###
