"""Drop project_id from drone_inspections

Revision ID: f1a1331ea5d3
Revises: 150b38f615ff
Create Date: 2025-07-29 17:55:58.679789+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1a1331ea5d3"
down_revision: str | None = "150b38f615ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        f"ix_{schema}_drone_inspections_project_id",
        table_name="drone_inspections",
        schema=schema,
    )
    op.drop_constraint(
        op.f("drone_inspections_project_id_fkey"),
        "drone_inspections",
        schema=schema,
        type_="foreignkey",
    )
    op.drop_column("drone_inspections", "project_id", schema=schema)
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drone_inspections",
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
        schema=schema,
    )
    op.create_foreign_key(
        op.f("drone_inspections_project_id_fkey"),
        "drone_inspections",
        "projects",
        ["project_id"],
        ["project_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    op.create_index(
        op.f("ix_project_default_drone_inspections_project_id"),
        "drone_inspections",
        ["project_id"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###
