"""Add default for projects.active

Revision ID: d446e0b2804f
Revises: 652e535cf2a6
Create Date: 2025-07-30 22:02:35.891630+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d446e0b2804f"
down_revision: str | None = "652e535cf2a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "active",
        server_default="FALSE",
        existing_type=sa.BOOLEAN(),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "active",
        server_default=None,
        existing_type=sa.BOOLEAN(),
        schema="operational",
    )
    # ### end Alembic commands ###
