"""add NOT NULL and UNIQUE to name_scada

Revision ID: 0fadaaf46198
Revises: fd69a0497d2a
Create Date: 2025-07-01 14:49:10.233592+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fadaaf46198"
down_revision: str | None = "fd69a0497d2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tags", "name_scada", existing_type=sa.VARCHAR(), nullable=False, schema=schema
    )
    op.create_unique_constraint(None, "tags", ["name_scada"], schema=schema)
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", schema=schema, type_="unique")
    op.alter_column(
        "tags", "name_scada", existing_type=sa.VARCHAR(), nullable=True, schema=schema
    )
    # ### end Alembic commands ###
