"""Drop <project>.kpi_data tables

Revision ID: 29d69706c5f5
Revises: f16dec2ec6ff
Create Date: 2025-06-09 15:55:17.209314+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "29d69706c5f5"
down_revision: str | None = "f16dec2ec6ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("kpi_data_time_idx", table_name="kpi_data", schema=schema)
    op.drop_table("kpi_data", schema=schema)
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_data",
        sa.Column(
            "time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("kpi_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "json",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "summary_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["kpi_type_id"],
            ["operational.kpi_types.kpi_type_id"],
            name="kpi_data_kpi_type_id_fkey",
        ),
        sa.PrimaryKeyConstraint("time", "kpi_type_id", name="kpi_data_pkey"),
        schema=schema,
    )
    op.create_index(
        "kpi_data_time_idx",
        "kpi_data",
        [sa.literal_column("time DESC")],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###
