"""Add operational.kpi_data

Revision ID: 7ce035abffd3
Revises: 9ad32afa9396
Create Date: 2025-01-18 21:07:12.046821+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7ce035abffd3"
down_revision: str | None = "9ad32afa9396"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_data",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("kpi_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "device_data_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("project_data", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["kpi_type_id"],
            ["operational.kpi_types.kpi_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("date", "project_id", "kpi_type_id"),
        schema="operational",
    )
    op.create_index(
        "kpi_data_kpi_type_id_date_idx",
        "kpi_data",
        ["kpi_type_id", sa.text("date DESC")],
        unique=False,
        schema="operational",
    )
    op.create_index(
        "kpi_data_project_id_date_idx",
        "kpi_data",
        ["project_id", sa.text("date DESC")],
        unique=False,
        schema="operational",
    )
    op.create_index(
        "kpi_data_project_id_kpi_type_id_date_idx",
        "kpi_data",
        ["project_id", "kpi_type_id", sa.text("date DESC")],
        unique=False,
        schema="operational",
    )
    op.execute(
        """
        SELECT create_hypertable(
            'operational.kpi_data',
            by_range('date'),
            create_default_indexes => FALSE
        );
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "kpi_data_project_id_kpi_type_id_date_idx",
        table_name="kpi_data",
        schema="operational",
    )
    op.drop_index(
        "kpi_data_project_id_date_idx",
        table_name="kpi_data",
        schema="operational",
    )
    op.drop_index(
        "kpi_data_kpi_type_id_date_idx",
        table_name="kpi_data",
        schema="operational",
    )
    op.drop_table("kpi_data", schema="operational")
    # ### end Alembic commands ###
