"""add bifaciality_factor and cells_in_paralle to pv_modules

Revision ID: edb51ae438cb
Revises: 0d80eb71fba4
Create Date: 2025-07-18 03:05:30.192367+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edb51ae438cb"
down_revision: str | None = "0d80eb71fba4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_modules",
        sa.Column(
            "bifaciality_factor", sa.Float(), server_default="0.0", nullable=False
        ),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column(
            "cells_in_parallel", sa.SmallInteger(), server_default="1", nullable=False
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_modules", "cells_in_parallel", schema="operational")
    op.drop_column("pv_modules", "bifaciality_factor", schema="operational")
    # ### end Alembic commands ###
