"""Add notify_offsets and notify_method to calendar_items

Revision ID: ef2d9b1532f2
Revises: f8362a212a41
Create Date: 2025-05-16 02:46:45.226297+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef2d9b1532f2"
down_revision: str | None = "f8362a212a41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "calendar_item_categories_long_name_key",
        "calendar_item_categories",
        schema="operational",
        type_="unique",
    )
    op.drop_constraint(
        "calendar_item_categories_short_name_key",
        "calendar_item_categories",
        schema="operational",
        type_="unique",
    )
    op.add_column(
        "calendar_items",
        sa.Column("notify_offsets", sa.ARRAY(sa.String()), nullable=True),
        schema="operational",
    )
    op.add_column(
        "calendar_items",
        sa.Column("notify_method", sa.ARRAY(sa.String()), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calendar_items", "notify_method", schema="operational")
    op.drop_column("calendar_items", "notify_offsets", schema="operational")
    op.create_unique_constraint(
        "calendar_item_categories_short_name_key",
        "calendar_item_categories",
        ["short_name"],
        schema="operational",
    )
    op.create_unique_constraint(
        "calendar_item_categories_long_name_key",
        "calendar_item_categories",
        ["long_name"],
        schema="operational",
    )
    # ### end Alembic commands ###
