"""add has_backtracking optional bool to project table

Revision ID: 7d46ea4642d0
Revises: e6852416cfa4
Create Date: 2025-04-06 12:16:57.151732+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d46ea4642d0"
down_revision: str | None = "e6852416cfa4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("has_backtracking", sa.Boolean(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "has_backtracking", schema="operational")
    # ### end Alembic commands ###
