"""add gsheet_id to projects table

Revision ID: 4f54ece41407
Revises: 7d46ea4642d0
Create Date: 2025-04-07 23:37:20.895603+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f54ece41407"
down_revision: str | None = "7d46ea4642d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("gsheet_id", sa.String(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "gsheet_id", schema="operational")
    # ### end Alembic commands ###
