"""added half-cut as a column in the pv_modules table

Revision ID: d3195dc23a25
Revises: c333397c0363
Create Date: 2025-04-03 14:58:23.445362+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3195dc23a25"
down_revision: str | None = "c333397c0363"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_modules",
        sa.Column("half_cut", sa.Boolean(), server_default="true", nullable=False),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pv_modules", "half_cut", schema="operational")
    # ### end Alembic commands ###
