"""add pvsyst parameters for single diode model

Revision ID: 76dc71b10705
Revises: bdd9b9e351c5
Create Date: 2025-08-14 22:40:50.327171+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76dc71b10705"
down_revision: str | None = "bdd9b9e351c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pv_modules",
        sa.Column("r_shunt_0", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("r_shunt_exponent", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("diode_ideality_factor", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pv_modules",
        sa.Column("diode_ideality_factor_temp_coefficient", sa.Float(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "pv_modules", "diode_ideality_factor_temp_coefficient", schema="operational"
    )
    op.drop_column("pv_modules", "diode_ideality_factor", schema="operational")
    op.drop_column("pv_modules", "r_shunt_exponent", schema="operational")
    op.drop_column("pv_modules", "r_shunt_0", schema="operational")
    # ### end Alembic commands ###
