"""add company to PV equipment

Revision ID: a0f3bd16b031
Revises: ef2d9b1532f2
Create Date: 2025-05-27 18:59:00.227780+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0f3bd16b031"
down_revision: str | None = "ef2d9b1532f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inverters",
        sa.Column(
            "company_id",
            sa.UUID(),
            server_default="01959294-3e51-4d3e-9f57-e9c2c3635c84",
            nullable=False,
        ),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "inverters",
        "companies",
        ["company_id"],
        ["company_id"],
        source_schema="operational",
        referent_schema="admin",
    )
    op.add_column(
        "pv_modules",
        sa.Column(
            "company_id",
            sa.UUID(),
            server_default="01959294-3e51-4d3e-9f57-e9c2c3635c84",
            nullable=False,
        ),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "pv_modules",
        "companies",
        ["company_id"],
        ["company_id"],
        source_schema="operational",
        referent_schema="admin",
    )
    op.add_column(
        "rackings",
        sa.Column(
            "company_id",
            sa.UUID(),
            server_default="01959294-3e51-4d3e-9f57-e9c2c3635c84",
            nullable=False,
        ),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "rackings",
        "companies",
        ["company_id"],
        ["company_id"],
        source_schema="operational",
        referent_schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rackings", schema="operational", type_="foreignkey")
    op.drop_column("rackings", "company_id", schema="operational")
    op.drop_constraint(None, "pv_modules", schema="operational", type_="foreignkey")
    op.drop_column("pv_modules", "company_id", schema="operational")
    op.drop_constraint(None, "inverters", schema="operational", type_="foreignkey")
    op.drop_column("inverters", "company_id", schema="operational")
    # ### end Alembic commands ###
