"""Add drone_inspections and drone_anomalies

Revision ID: a65ac72eed54
Revises: f77b0a9cea04
Create Date: 2025-07-24 19:03:51.050666+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a65ac72eed54"
down_revision: str | None = "f77b0a9cea04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drone_inspections",
        sa.Column("inspection_uuid", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("inspection_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("upload_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service_tier", sa.String(), nullable=True),
        sa.Column("total_power_loss_kw", sa.Float(), nullable=True),
        sa.Column("total_power_loss_percent", sa.Float(), nullable=True),
        sa.Column("total_affected_modules", sa.Integer(), nullable=True),
        sa.Column("report_summary", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("inspection_uuid"),
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_drone_inspections_project_id"),
        "drone_inspections",
        ["project_id"],
        unique=False,
        schema=schema,
    )
    op.create_table(
        "drone_anomalies",
        sa.Column("anomaly_uuid", sa.Uuid(), nullable=False),
        sa.Column("inspection_uuid", sa.Uuid(), nullable=False),
        sa.Column("stack_id", sa.String(), nullable=True),
        sa.Column("ir_signal", sa.String(), nullable=True),
        sa.Column("rgb_signal", sa.String(), nullable=True),
        sa.Column("subsystem", sa.String(), nullable=True),
        sa.Column("remediation_category", sa.String(), nullable=True),
        sa.Column("energy_loss_weighting", sa.Float(), nullable=True),
        sa.Column("power_loss_kw", sa.Float(), nullable=True),
        sa.Column("location_lat", sa.Float(), nullable=True),
        sa.Column("location_lon", sa.Float(), nullable=True),
        sa.Column("client_status_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inspection_uuid"],
            [f"{schema}.drone_inspections.inspection_uuid"],
        ),
        sa.PrimaryKeyConstraint("anomaly_uuid"),
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_drone_anomalies_inspection_uuid"),
        "drone_anomalies",
        ["inspection_uuid"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f(f"ix_{schema}_drone_anomalies_inspection_uuid"),
        table_name="drone_anomalies",
        schema=schema,
    )
    op.drop_table("drone_anomalies", schema=schema)
    op.drop_index(
        op.f(f"ix_{schema}_drone_inspections_project_id"),
        table_name="drone_inspections",
        schema=schema,
    )
    op.drop_table("drone_inspections", schema=schema)
    # ### end Alembic commands ###
