"""Add has_bess_enclosures column to projects table

Revision ID: 9ad32afa9396
Revises: 632304ba89d7
Create Date: 2025-01-14 22:40:56.641032+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ad32afa9396"
down_revision: str | None = "632304ba89d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "has_bess_enclosures",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "has_bess_enclosures", schema="operational")
    # ### end Alembic commands ###
