"""Add operational.cmms_integrations and cmms_permissions tables

Revision ID: 64dde206babc
Revises: 3565d3258a23
Create Date: 2025-04-17 23:06:41.345759+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64dde206babc"
down_revision: str | None = "3565d3258a23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cmms_integrations",
        sa.Column(
            "cmms_integration_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("cmms_provider_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cmms_provider_id"],
            ["operational.cmms_providers.cmms_provider_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("cmms_integration_id"),
        schema="operational",
    )
    op.create_table(
        "cmms_permissions",
        sa.Column("cmms_integration_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("can_view", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.ForeignKeyConstraint(
            ["cmms_integration_id"],
            ["operational.cmms_integrations.cmms_integration_id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.PrimaryKeyConstraint("cmms_integration_id", "company_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cmms_permissions", schema="operational")
    op.drop_table("cmms_integrations", schema="operational")
    # ### end Alembic commands ###
