"""Drop operational.trees table

Revision ID: f16dec2ec6ff
Revises: a149bf6204da
Create Date: 2025-06-09 15:42:17.857969+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f16dec2ec6ff"
down_revision: str | None = "a149bf6204da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trees", schema="operational")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trees",
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "all_devices_and_tags",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
            name="trees_project_id_fkey",
        ),
        sa.PrimaryKeyConstraint("project_id", name="trees_pkey"),
        schema="operational",
    )
    # ### end Alembic commands ###
