"""Add NOT NULL constraint to events.time_start

Revision ID: 97c331e0c1f8
Revises: 8bf14dcc0a59
Create Date: 2025-01-03 20:03:27.532471+00:00

"""

from collections.abc import Sequence

from _alembic_migrations.tenant import for_each_project_schema
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "97c331e0c1f8"
down_revision: str | None = "8bf14dcc0a59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "time_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "time_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        schema=schema,
    )
    # ### end Alembic commands ###
