"""Add operational.projects.data_receive_schedule

Revision ID: 8fbe37f86d6c
Revises: 21ea67400d81
Create Date: 2025-06-13 18:47:57.683020+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fbe37f86d6c"
down_revision: str | None = "21ea67400d81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("data_receive_schedule", sa.String(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "data_receive_schedule", schema="operational")
    # ### end Alembic commands ###
