"""Change type of device_id_path to ltree

Revision ID: bfadcc9bf14f
Revises: 4fab95f099bb
Create Date: 2025-02-06 18:29:25.305873+00:00

"""

from collections.abc import Sequence

import core.models
import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfadcc9bf14f"
down_revision: str | None = "4fab95f099bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "devices",
        "device_id_path",
        existing_type=sa.VARCHAR(),
        type_=core.models.LTree(),
        postgresql_using="device_id_path::ltree",
        existing_nullable=True,
        schema=schema,
    )
    op.create_index(
        "ix_devices_device_id_path",
        "devices",
        ["device_id_path"],
        unique=False,
        schema=schema,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_devices_device_id_path",
        table_name="devices",
        schema=schema,
        postgresql_using="gist",
    )
    op.alter_column(
        "devices",
        "device_id_path",
        existing_type=core.models.LTree(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        schema=schema,
    )
    # ### end Alembic commands ###
