"""Update device_models unique constraint

Revision ID: 4df1c2d5f31b
Revises: 49cbf5f180d9
Create Date: 2026-04-22 22:12:34.404310+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4df1c2d5f31b"
down_revision: str | None = "49cbf5f180d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_device_models_device_type_id_brand_model"),
        "device_models",
        schema="operational",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_device_models_company_id_device_type_id_model",
        "device_models",
        ["company_id", "device_type_id", "model"],
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_device_models_company_id_device_type_id_model",
        "device_models",
        schema="operational",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_device_models_device_type_id_brand_model"),
        "device_models",
        ["device_type_id", "brand", "model"],
        schema="operational",
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
