"""Add project issues tables

Revision ID: 09364c6d5d8f
Revises: 2dd4953b6919
Create Date: 2026-04-21 17:47:04.517843+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09364c6d5d8f"
down_revision: str | None = "2dd4953b6919"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_updates",
        sa.Column("issue_update_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("issue_state_id", sa.Integer(), nullable=False),
        sa.Column("state_time_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state_changed_source", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            [f"{schema}.issues.issue_id"],
            name=op.f("issue_updates_issue_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["issue_state_id"],
            ["operational.issue_states.issue_state_id"],
            name=op.f("issue_updates_issue_state_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("issue_update_id"),
        schema=schema,
    )
    op.add_column(
        "issues",
        sa.Column("tag_id", sa.Integer(), nullable=True),
        schema=schema,
    )
    op.add_column(
        "issues",
        sa.Column("issue_category_id", sa.Integer(), nullable=False),
        schema=schema,
    )
    op.add_column(
        "issues",
        sa.Column(
            "detector_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        schema=schema,
    )
    op.drop_constraint(
        op.f("issues_sensor_type_id_fkey"),
        "issues",
        schema=schema,
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("issues_failure_mode_id_fkey"),
        "issues",
        schema=schema,
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("issues_tag_id_fkey"),
        "issues",
        "tags",
        ["tag_id"],
        ["tag_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        op.f("issues_issue_category_id_fkey"),
        "issues",
        "issue_categories",
        ["issue_category_id"],
        ["issue_category_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    op.drop_column("issues", "failure_mode_id", schema=schema)
    op.drop_column("issues", "time_detected", schema=schema)
    op.drop_column("issues", "version", schema=schema)
    op.drop_column("issues", "sensor_type_id", schema=schema)
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issues",
        sa.Column("sensor_type_id", sa.INTEGER(), autoincrement=False, nullable=True),
        schema=schema,
    )
    op.add_column(
        "issues",
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema=schema,
    )
    op.add_column(
        "issues",
        sa.Column(
            "time_detected",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        schema=schema,
    )
    op.add_column(
        "issues",
        sa.Column(
            "failure_mode_id",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        schema=schema,
    )
    op.drop_constraint(
        op.f("issues_issue_category_id_fkey"),
        "issues",
        schema=schema,
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("issues_tag_id_fkey"),
        "issues",
        schema=schema,
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("issues_failure_mode_id_fkey"),
        "issues",
        "failure_modes",
        ["failure_mode_id"],
        ["failure_mode_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    op.create_foreign_key(
        op.f("issues_sensor_type_id_fkey"),
        "issues",
        "sensor_types",
        ["sensor_type_id"],
        ["sensor_type_id"],
        source_schema=schema,
        referent_schema="operational",
    )
    op.drop_column("issues", "detector_metadata", schema=schema)
    op.drop_column("issues", "issue_category_id", schema=schema)
    op.drop_column("issues", "tag_id", schema=schema)
    op.drop_table("issue_updates", schema=schema)
    # ### end Alembic commands ###
