"""add name short to notification type

Revision ID: 234336a23dfb
Revises: ee077a618e7e
Create Date: 2026-03-19 21:20:41.322726+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "234336a23dfb"
down_revision: str | None = "ee077a618e7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_types",
        sa.Column("name_short", sa.String(), nullable=True),
        schema="admin",
    )
    op.alter_column(
        "notification_types",
        "name_long",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        schema="admin",
    )
    op.create_unique_constraint(
        None, "notification_types", ["name_short"], schema="admin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notification_types", schema="admin", type_="unique")
    op.alter_column(
        "notification_types",
        "name_long",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        schema="admin",
    )
    op.drop_column("notification_types", "name_short", schema="admin")
    # ### end Alembic commands ###
