"""Make device_types.description NOT NULL

Revision ID: 995a8f6e27ba
Revises: 8d8ab1895ffc
Create Date: 2026-04-10 14:56:08.877111+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "995a8f6e27ba"
down_revision: str | None = "8d8ab1895ffc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "device_types",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "device_types",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="operational",
    )
    # ### end Alembic commands ###
