"""Drop kpi_alerts

Revision ID: d2f3bbc73e64
Revises: c6b1beb44648
Create Date: 2026-02-10 12:33:17.212386+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d2f3bbc73e64"
down_revision: str | None = "c6b1beb44648"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kpi_alerts", schema="operational")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_alerts",
        sa.Column(
            "kpi_alert_id",
            sa.SMALLINT(),
            server_default=sa.text(
                "nextval('operational.kpi_alerts_kpi_alert_id_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("kpi_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kpi_type_id"],
            ["operational.kpi_types.kpi_type_id"],
            name=op.f("kpi_alerts_kpi_type_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
            name=op.f("kpi_alerts_project_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["admin.users.user_id"], name=op.f("kpi_alerts_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("kpi_alert_id", name=op.f("kpi_alerts_pkey")),
        schema="operational",
    )
    # ### end Alembic commands ###
