"""add operational issue tables

Revision ID: 3bf95b662843
Revises: bcdac7962331
Create Date: 2026-04-20 21:50:10.384354+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bf95b662843"
down_revision: str | None = "bcdac7962331"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_categories",
        sa.Column(
            "issue_category_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("issue_category_id"),
        sa.UniqueConstraint("name_long"),
        schema="operational",
    )
    op.create_table(
        "issue_states",
        sa.Column("issue_state_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("issue_state_id"),
        sa.UniqueConstraint("name_long"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("issue_states", schema="operational")
    op.drop_table("issue_categories", schema="operational")
    # ### end Alembic commands ###
