"""add notification enum tables

Revision ID: 2dd4953b6919
Revises: 3bf95b662843
Create Date: 2026-04-21 17:13:28.922907+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dd4953b6919"
down_revision: str | None = "3bf95b662843"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_channels",
        sa.Column(
            "notification_channel_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("notification_channel_id"),
        sa.UniqueConstraint("name_short"),
        schema="admin",
    )
    op.create_table(
        "notification_severities",
        sa.Column(
            "notification_severity_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("notification_severity_id"),
        sa.UniqueConstraint("name_short"),
        schema="admin",
    )
    op.create_table(
        "notification_state_enums",
        sa.Column(
            "notification_state_enum_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("notification_state_enum_id"),
        sa.UniqueConstraint("name_short"),
        schema="admin",
    )
    op.create_table(
        "reaction_types",
        sa.Column(
            "reaction_type_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("reaction_type_id"),
        sa.UniqueConstraint("name_short"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reaction_types", schema="admin")
    op.drop_table("notification_state_enums", schema="admin")
    op.drop_table("notification_severities", schema="admin")
    op.drop_table("notification_channels", schema="admin")
    # ### end Alembic commands ###
