"""Add access_date_start to company_projects

Revision ID: c6b1beb44648
Revises: 530731d657ec
Create Date: 2026-02-09 21:11:25.448473+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6b1beb44648"
down_revision: str | None = "530731d657ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_projects",
        sa.Column("data_access_start", sa.Date(), nullable=True),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_projects", "data_access_start", schema="admin")
    # ### end Alembic commands ###
