import { PageError } from '@/components/Error'
import { PageLoader } from '@/components/Loading'
import { PageTitle } from '@/components/PageTitle'
import { useGetProjectReportInstances } from '@/hooks/api'
import { ReportInstance } from '@/hooks/types'
import {
  Divider,
  Group,
  Paper,
  SimpleGrid,
  Space,
  Stack,
  Text,
  Tooltip,
} from '@mantine/core'
import {
  IconCalendarEvent,
  IconCalendarWeek,
  IconEyeOff,
  IconFileTypeCsv,
  IconFileTypePdf,
  IconFileTypeXls,
} from '@tabler/icons-react'
import { Link, useParams } from 'react-router'

import styles from './ProjectReports.module.css'

// Report metadata configuration
// NOTE: In the future some of this information could be moved to the database
const REPORT_CONFIG: {
  link: Record<number, string> // The link to the report page
  description: Record<number, string> // The description of the report
  selectable_date: Record<number, boolean> // Whether the report has a selectable date
  selectable_date_range: Record<number, boolean> // Whether the report has a selectable date range
  downloadable_excel: Record<number, boolean> // Whether the report has a downloadable Excel file
  downloadable_csv: Record<number, boolean> // Whether the report has a downloadable CSV file
  downloadable_pdf: Record<number, boolean> // Whether the report has a downloadable PDF file
} = {
  link: {
    2: 'dc-amperage',
    3: 'module-degradation',
    4: 'tracker-availability?report_type_id=4',
    5: 'tracker-availability?report_type_id=5',
    6: 'inverter-availability',
    8: 'pcs-apparent-vs-voltage',
    9: 'daily-performance',
  },
  description: {
    2: 'This report is designed to characterize the normalized output current of combiners at a project. The analysis is generated with user input for clearsky data, then combiner current is normalized based on relative capacity and compared to both neighboring and project-wide combiner results.',
    3: 'This report is designed to characterize the performance of the modules at the most granular level possible. The analysis is generated by heavily filtering data for clearsky, high-performance timestamps which guarantee that shortfalls can be attributed to module degradation or other DC performance issues.',
    4: 'This report is designed to analyze the performance of trackers compared to their own setpoints. The downloadable Excel file allows the tuning of these parameters for more specific analysis.',
    5: 'This report is designed to analyze the performance of trackers compared to the median setpoint of their associated NCU. The downloadable Excel file allows the tuning of these parameters for more specific analysis.',
    6: 'This report is designed to analyze the mechanical availability of inverters and inverter modules. The report is user-tunable to allow for analysis of availability based on user-defined parameters.',
    8: 'This report visualizes the relationship between inverter apparent power output (in MVA) and terminal AC voltage. A theoretical envelope is included to illustrate expected voltage behavior under normal operating conditions.',
    9: 'This report provides a comprehensive daily performance overview, including project generation, performance ratio, PCS mechanical availability, and event tracking. It features a 30-day trailing energy analysis and DC combiner field health visualization.',
  },
  selectable_date: {
    2: true,
    4: true,
    5: true,
    6: true,
    9: true,
  },
  selectable_date_range: {
    3: true,
    8: true,
  },
  downloadable_excel: {
    2: true,
    4: true,
    5: true,
    6: true,
  },
  downloadable_csv: {
    3: true,
  },
  downloadable_pdf: {
    9: true,
  },
}

const Page = () => {
  // Get the project ID from the URL
  const { projectId } = useParams<{ projectId: string }>()

  // Get report instances for the project
  const reportInstances = useGetProjectReportInstances({
    pathParams: { projectId: projectId || '' },
    queryParams: {
      deep: true,
    },
  })

  // Early return for loading and error states
  if (reportInstances.isLoading) return <PageLoader />
  if (reportInstances.error) return <PageError error={reportInstances.error} />

  return (
    <Stack p="md" h="100%">
      <PageTitle info="This page provides access to various project reports. Click on a report to view more details.">
        Reports
      </PageTitle>

      {reportInstances.data?.length === 0 ? (
        // If no reports are available, show a message
        <Text c="dimmed">No reports available for this project.</Text>
      ) : (
        // Otherwise, show the report instance cards
        <SimpleGrid cols={{ base: 1, sm: 2, md: 4, lg: 5, xl: 6 }}>
          {reportInstances.data
            ?.filter(
              (reportInstance) =>
                reportInstance.report_type_id in REPORT_CONFIG.link,
            )
            .map((reportInstance) => (
              <ReportInstanceCard
                key={reportInstance.report_type_id}
                reportInstance={reportInstance}
              />
            ))}
        </SimpleGrid>
      )}
    </Stack>
  )
}

const ReportInstanceCard = ({
  reportInstance,
}: {
  reportInstance: ReportInstance
}) => {
  const iconSize = 20
  const excelGreen = '#0F7C41'
  const pdfRed = '#EB1F00'

  const link = REPORT_CONFIG.link[reportInstance.report_type_id]
  const description = REPORT_CONFIG.description[reportInstance.report_type_id]

  return (
    <Link to={link} style={{ textDecoration: 'none', color: 'inherit' }}>
      <Paper
        withBorder
        p="md"
        radius="md"
        className={styles.element}
        style={{ cursor: 'pointer' }}
        shadow="md"
        h={400}
      >
        <Stack h="100%">
          {/* Visibility icon and report title */}
          <Group>
            {!reportInstance.is_visible && (
              <IconEyeOff size={iconSize} color="red" />
            )}
            <Text fw={700}>{reportInstance.report_type?.name_long}</Text>
          </Group>

          {/* Description and description */}
          <Divider />
          {description && <Text size="sm">{description}</Text>}
          <Space flex={1} />

          {/* Information icons */}
          <Group justify="end">
            {REPORT_CONFIG.selectable_date[reportInstance.report_type_id] && (
              <Tooltip label="Selectable date">
                <IconCalendarEvent size={iconSize} />
              </Tooltip>
            )}
            {REPORT_CONFIG.selectable_date_range[
              reportInstance.report_type_id
            ] && (
              <Tooltip label="Selectable date range">
                <IconCalendarWeek size={iconSize} />
              </Tooltip>
            )}
            {REPORT_CONFIG.downloadable_excel[
              reportInstance.report_type_id
            ] && (
              <Tooltip label="Excel download available">
                <IconFileTypeXls size={iconSize} color={excelGreen} />
              </Tooltip>
            )}
            {REPORT_CONFIG.downloadable_csv[reportInstance.report_type_id] && (
              <Tooltip label="CSV download available">
                <IconFileTypeCsv size={iconSize} color={excelGreen} />
              </Tooltip>
            )}
            {REPORT_CONFIG.downloadable_pdf[reportInstance.report_type_id] && (
              <Tooltip label="PDF download available">
                <IconFileTypePdf size={iconSize} color={pdfRed} />
              </Tooltip>
            )}
          </Group>
        </Stack>
      </Paper>
    </Link>
  )
}

export default Page
