"""add qse_fields table

Revision ID: 5bca67c2d4e5
Revises: e9685da898cd
Create Date: 2025-10-30 14:57:40.296121+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bca67c2d4e5"
down_revision: str | None = "e9685da898cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#   `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qse_fields",
        sa.Column("qse_provider_id", sa.Integer(), nullable=False),
        sa.Column("qse_field_name", sa.String(), nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("unit_offset", sa.Double(), nullable=True),
        sa.Column("unit_scale", sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qse_provider_id"],
            ["operational.qse_providers.qse_provider_id"],
        ),
        sa.PrimaryKeyConstraint("qse_provider_id", "qse_field_name"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("qse_fields", schema="operational")
    # ### end Alembic commands ###
