"""create QSE tables

Revision ID: e9685da898cd
Revises: a969424d771c
Create Date: 2025-10-28 17:25:07.375874+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9685da898cd"
down_revision: str | None = "a969424d771c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qse_providers",
        sa.Column("qse_provider_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("qse_provider_id"),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    op.create_table(
        "qse_integrations",
        sa.Column(
            "qse_integration_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("qse_provider_id", sa.Integer(), nullable=False),
        sa.Column("qse_project_identifier", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["qse_provider_id"],
            ["operational.qse_providers.qse_provider_id"],
        ),
        sa.PrimaryKeyConstraint("qse_integration_id"),
        schema="operational",
    )
    op.create_table(
        "qse_permissions",
        sa.Column("qse_integration_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("can_view", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["qse_integration_id"],
            ["operational.qse_integrations.qse_integration_id"],
        ),
        sa.PrimaryKeyConstraint("qse_integration_id", "company_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("qse_permissions", schema="operational")
    op.drop_table("qse_integrations", schema="operational")
    op.drop_table("qse_providers", schema="operational")
    # ### end Alembic commands ###
