"""

Revision ID: 45236b1f900f
Revises: 4806009c1b41
Create Date: 2025-12-04 21:46:52.006750+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45236b1f900f"
down_revision: str | None = "4806009c1b41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("sensor_type_id", sa.Integer(), nullable=True),
        sa.Column("failure_mode_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("time_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_detected", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["project_default.devices.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["operational.failure_modes.failure_mode_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sensor_type_id"],
            ["operational.sensor_types.sensor_type_id"],
        ),
        sa.PrimaryKeyConstraint("issue_id"),
        schema=schema,
    )
    op.create_index(
        op.f("ix_project_default_issues_device_id"),
        "issues",
        ["device_id"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_default_issues_device_id"), table_name="issues", schema=schema
    )
    op.drop_table("issues", schema=schema)
    # ### end Alembic commands ###
