"""

Revision ID: 52ce56be026d
Revises: 133d49eecf35
Create Date: 2025-10-09 15:48:02.222478+00:00

"""

from collections.abc import Sequence

from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52ce56be026d"
down_revision: str | None = "133d49eecf35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("events_device_id_time_start_key"), "events", schema=schema, type_="unique"
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("events_device_id_time_start_key"),
        "events",
        ["device_id", "time_start"],
        schema=schema,
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
