"""add daily financial loss column

Revision ID: ad0e8529845f
Revises: 5bca67c2d4e5
Create Date: 2025-11-07 00:28:35.915078+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad0e8529845f"
down_revision: str | None = "5bca67c2d4e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("loss_daily_financial", sa.Double(), nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "loss_daily_financial", schema=schema)
    # ### end Alembic commands ###
