"""

Revision ID: 62df320c6a28
Revises: 45236b1f900f
Create Date: 2025-12-08 21:54:23.907672+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62df320c6a28"
down_revision: str | None = "45236b1f900f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_cmms_tickets",
        sa.Column(
            "event_cmms_ticket_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("cmms_ticket_id", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cmms_ticket_id"],
            [f"{schema}.cmms_tickets.cmms_ticket_id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["admin.users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            [f"{schema}.events.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_cmms_ticket_id"),
        sa.UniqueConstraint("event_id", "cmms_ticket_id"),
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_event_cmms_tickets_cmms_ticket_id"),
        "event_cmms_tickets",
        ["cmms_ticket_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_event_cmms_tickets_created_by_user_id"),
        "event_cmms_tickets",
        ["created_by_user_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_event_cmms_tickets_event_id"),
        "event_cmms_tickets",
        ["event_id"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f(f"ix_{schema}_event_cmms_tickets_event_id"),
        table_name="event_cmms_tickets",
        schema=schema,
    )
    op.drop_index(
        op.f(f"ix_{schema}_event_cmms_tickets_created_by_user_id"),
        table_name="event_cmms_tickets",
        schema=schema,
    )
    op.drop_index(
        op.f(f"ix_{schema}_event_cmms_tickets_cmms_ticket_id"),
        table_name="event_cmms_tickets",
        schema=schema,
    )
    op.drop_table("event_cmms_tickets", schema=schema)
    # ### end Alembic commands ###
