"""Custom dashboard shares

Revision ID: 159ebb4a0c6e
Revises: a6bd4a6b1449
Create Date: 2025-12-09 21:23:29.137633+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "159ebb4a0c6e"
down_revision: str | None = "a6bd4a6b1449"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_dashboard_shares",
        sa.Column("share_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dashboard_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dashboard_id"],
            ["operational.custom_dashboards.dashboard_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("share_id"),
        sa.UniqueConstraint("dashboard_id", "user_id"),
        schema="operational",
    )
    op.create_index(
        op.f("ix_operational_custom_dashboard_shares_dashboard_id"),
        "custom_dashboard_shares",
        ["dashboard_id"],
        unique=False,
        schema="operational",
    )
    op.create_index(
        op.f("ix_operational_custom_dashboard_shares_user_id"),
        "custom_dashboard_shares",
        ["user_id"],
        unique=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_operational_custom_dashboard_shares_user_id"),
        table_name="custom_dashboard_shares",
        schema="operational",
    )
    op.drop_index(
        op.f("ix_operational_custom_dashboard_shares_dashboard_id"),
        table_name="custom_dashboard_shares",
        schema="operational",
    )
    op.drop_table("custom_dashboard_shares", schema="operational")
    # ### end Alembic commands ###
