"""Add event_id column to drone_anomalies table

Revision ID: a969424d771c
Revises: 52ce56be026d
Create Date: 2025-10-09 21:16:55.432814+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a969424d771c"
down_revision: str | None = "52ce56be026d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drone_anomalies",
        sa.Column("event_id", sa.Integer(), nullable=True),
        schema=schema,
    )
    op.create_index(
        op.f("ix_project_default_drone_anomalies_event_id"),
        "drone_anomalies",
        ["event_id"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        None,
        "drone_anomalies",
        "events",
        ["event_id"],
        ["event_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "drone_anomalies", schema=schema, type_="foreignkey")
    op.drop_index(
        op.f("ix_project_default_drone_anomalies_event_id"),
        table_name="drone_anomalies",
        schema=schema,
    )
    op.drop_column("drone_anomalies", "event_id", schema=schema)
    # ### end Alembic commands ###
