"""Allow NULLs in operational.pv_budgeted_data columns (ghi, temperature, soiling_percentage)

Revision ID: 133d49eecf35
Revises: ab0aa5131b88
Create Date: 2025-10-07 18:28:11.221774+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "133d49eecf35"
down_revision: str | None = "ab0aa5131b88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pv_budgeted_data",
        "ghi",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_comment="Global Horizontal Irradiance [W/m²]",
        schema="operational",
    )
    op.alter_column(
        "pv_budgeted_data",
        "temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_comment="Temperature [°C]",
        schema="operational",
    )
    op.alter_column(
        "pv_budgeted_data",
        "soiling_percentage",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_comment="Soiling loss as percentage [%]",
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pv_budgeted_data",
        "soiling_percentage",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_comment="Soiling loss as percentage [%]",
        schema="operational",
    )
    op.alter_column(
        "pv_budgeted_data",
        "temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_comment="Temperature [°C]",
        schema="operational",
    )
    op.alter_column(
        "pv_budgeted_data",
        "ghi",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_comment="Global Horizontal Irradiance [W/m²]",
        schema="operational",
    )
    # ### end Alembic commands ###
