"""

Revision ID: a6bd4a6b1449
Revises: 62df320c6a28
Create Date: 2025-12-09 19:24:51.190629+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import MetaData

# revision identifiers, used by Alembic.
revision: str = "a6bd4a6b1449"
down_revision: str | None = "62df320c6a28"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions

ENUM_SEVERITY_NAME = "notification_severity"
ENUM_SEVERITY_VALUES = ["INFO", "WARNING", "CRITICAL"]
ENUM_CHANNEL_NAME = "notification_channel"
ENUM_CHANNEL_VALUES = ["EMAIL", "IN_APP"]
ENUM_STATE_NAME = "notification_state"
ENUM_STATE_VALUES = ["UNREAD", "READ", "DELETED"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    op.execute(
        f'CREATE TYPE "admin"."{ENUM_SEVERITY_NAME}" AS ENUM '
        f"({', '.join(repr(v) for v in ENUM_SEVERITY_VALUES)})"
    )
    op.execute(
        f'CREATE TYPE "admin"."{ENUM_CHANNEL_NAME}" AS ENUM '
        f"({', '.join(repr(v) for v in ENUM_CHANNEL_VALUES)})"
    )
    op.execute(
        f'CREATE TYPE "admin"."{ENUM_STATE_NAME}" AS ENUM '
        f"({', '.join(repr(v) for v in ENUM_STATE_VALUES)})"
    )

    severity_enum = sa.Enum(
        *ENUM_SEVERITY_VALUES,
        name=ENUM_SEVERITY_NAME,
        schema="admin",
        metadata=MetaData(schema="admin"),
    )
    channel_enum = sa.Enum(
        *ENUM_CHANNEL_VALUES,
        name=ENUM_CHANNEL_NAME,
        schema="admin",
        metadata=MetaData(schema="admin"),
    )
    state_enum = sa.Enum(
        *ENUM_STATE_VALUES,
        name=ENUM_STATE_NAME,
        schema="admin",
        metadata=MetaData(schema="admin"),
    )

    op.create_table(
        "notification_types",
        sa.Column("notification_type_id", sa.Integer(), nullable=False),
        sa.Column("name_long", sa.Text(), nullable=False),
        sa.Column("in_app_enabled_default", sa.Boolean(), nullable=False),
        sa.Column("email_enabled_default", sa.Boolean(), nullable=False),
        sa.Column(
            "in_app_severity_default",
            severity_enum,
            nullable=True,
        ),
        sa.Column(
            "email_severity_default",
            severity_enum,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("notification_type_id"),
        schema="admin",
    )
    op.create_table(
        "notification_preferences",
        sa.Column("notification_preference_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("notification_type_id", sa.Integer(), nullable=False),
        sa.Column("in_app_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "email_min_severity",
            severity_enum,
            nullable=False,
        ),
        sa.Column(
            "in_app_min_severity",
            severity_enum,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notification_type_id"],
            ["admin.notification_types.notification_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("notification_preference_id"),
        sa.UniqueConstraint("user_id", "project_id", "notification_type_id"),
        schema="admin",
    )
    op.create_table(
        "notifications",
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("notification_type_id", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "severity",
            severity_enum,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["notification_type_id"],
            ["admin.notification_types.notification_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("notification_id"),
        schema="admin",
    )
    op.create_table(
        "notification_states",
        sa.Column("notification_state_id", sa.Integer(), nullable=False),
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "channel",
            channel_enum,
            nullable=False,
        ),
        sa.Column(
            "state",
            state_enum,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["admin.notifications.notification_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("notification_state_id"),
        sa.UniqueConstraint("notification_id", "user_id", "channel"),
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_states", schema="admin")
    op.drop_table("notifications", schema="admin")
    op.drop_table("notification_preferences", schema="admin")
    op.drop_table("notification_types", schema="admin")

    op.execute(f'DROP TYPE IF EXISTS "admin"."{ENUM_STATE_NAME}" CASCADE')
    op.execute(f'DROP TYPE IF EXISTS "admin"."{ENUM_CHANNEL_NAME}" CASCADE')
    op.execute(f'DROP TYPE IF EXISTS "admin"."{ENUM_SEVERITY_NAME}" CASCADE')
    # ### end Alembic commands ###
