"""add project type to kpi type table

Revision ID: 1f2ee2640ca4
Revises: 5c0357ac7141
Create Date: 2026-03-05 20:53:47.559489+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f2ee2640ca4"
down_revision: str | None = "5c0357ac7141"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kpi_types",
        sa.Column("project_type_id", sa.SmallInteger(), nullable=True),
        schema="operational",
    )
    op.create_foreign_key(
        "fk_kpi_types_project_type_id",
        "kpi_types",
        "project_types",
        ["project_type_id"],
        ["project_type_id"],
        source_schema="operational",
        referent_schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_kpi_types_project_type_id",
        "kpi_types",
        schema="operational",
        type_="foreignkey",
    )
    op.drop_column("kpi_types", "project_type_id", schema="operational")
    # ### end Alembic commands ###
