"""Enforce not null on device_models.company_id

Revision ID: 49cbf5f180d9
Revises: d311ebc00a7e
Create Date: 2026-04-22 22:05:46.754761+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49cbf5f180d9"
down_revision: str | None = "d311ebc00a7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "device_models",
        "company_id",
        existing_type=sa.UUID(),
        nullable=False,
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "device_models",
        "company_id",
        existing_type=sa.UUID(),
        nullable=True,
        schema="operational",
    )
    # ### end Alembic commands ###
