"""Add renamed capacity columns to devices tables

Revision ID: 93d2244c759a
Revises: 58fda9d6be1a
Create Date: 2026-05-07 03:29:12.295505+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93d2244c759a"
down_revision: str | None = "58fda9d6be1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("capacity_power_ac_kw", sa.REAL(), nullable=True),
        schema=schema,
    )
    op.add_column(
        "devices",
        sa.Column("capacity_power_dc_kw", sa.REAL(), nullable=True),
        schema=schema,
    )
    op.add_column(
        "devices",
        sa.Column("capacity_energy_dc_kwh", sa.REAL(), nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "capacity_energy_dc_kwh", schema=schema)
    op.drop_column("devices", "capacity_power_dc_kw", schema=schema)
    op.drop_column("devices", "capacity_power_ac_kw", schema=schema)
    # ### end Alembic commands ###
