"""add provider_config to qse_integrations

Revision ID: 530731d657ec
Revises: ea9eb5c0484b
Create Date: 2026-02-02 04:22:33.821284+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "530731d657ec"
down_revision: str | None = "ea9eb5c0484b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "qse_integrations",
        sa.Column(
            "provider_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("qse_integrations", "provider_config", schema="operational")
    # ### end Alembic commands ###
