"""Add serial_number to devices tables

Revision ID: 9c74e6e1c8af
Revises: 4df1c2d5f31b
Create Date: 2026-04-28 17:34:35.334339+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c74e6e1c8af"
down_revision: str | None = "4df1c2d5f31b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices", sa.Column("serial_number", sa.String(), nullable=True), schema=schema
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "serial_number", schema=schema)
    # ### end Alembic commands ###
