"""create warranty tables to project schema

Revision ID: 5c0357ac7141
Revises: e02ead84e542
Create Date: 2026-02-25 15:24:49.656716+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op
from sqlalchemy.schema import MetaData

# revision identifiers, used by Alembic.
revision: str = "5c0357ac7141"
down_revision: str | None = "e02ead84e542"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and
#     `schema` arg in `upgrade` and `downgrade` functions


claim_status_enum = sa.Enum(
    "draft",
    "submitted",
    "in_progress",
    "resolved",
    "closed",
    name="claimstatus",
    schema="operational",
    metadata=MetaData(),
    create_type=False,
)

claim_update_type_enum = sa.Enum(
    "status_change",
    "submission",
    "oem_message",
    "note",
    "parts",
    "field_visit",
    name="claimupdatetype",
    schema="operational",
    metadata=MetaData(),
    create_type=False,
)


@for_each_project_schema
def _create_tables(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claims",
        sa.Column("claim_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("claim_config_id", sa.Integer(), nullable=False),
        sa.Column("status", claim_status_enum, nullable=False),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("external_reference", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_config_id"],
            ["operational.claim_configs.claim_config_id"],
        ),
        sa.PrimaryKeyConstraint("claim_id"),
        schema=schema,
    )
    op.create_table(
        "claim_devices",
        sa.Column("claim_device_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("oem_serial_number", sa.String(), nullable=True),
        sa.Column("oem_part_number", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            [f"{schema}.claims.claim_id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            [f"{schema}.devices.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            [f"{schema}.events.event_id"],
        ),
        sa.PrimaryKeyConstraint("claim_device_id"),
        schema=schema,
    )
    op.create_table(
        "claim_updates",
        sa.Column("claim_update_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("update_type", claim_update_type_enum, nullable=False),
        sa.Column("from_status", claim_status_enum, nullable=True),
        sa.Column("to_status", claim_status_enum, nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            [f"{schema}.claims.claim_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("claim_update_id"),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def _drop_tables(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claim_updates", schema=schema)
    op.drop_table("claim_devices", schema=schema)
    op.drop_table("claims", schema=schema)
    # ### end Alembic commands ###


def upgrade() -> None:
    op.execute(
        'CREATE TYPE "operational"."claimstatus" AS ENUM '
        "('draft', 'submitted', 'in_progress',"
        " 'resolved', 'closed')"
    )
    op.execute(
        'CREATE TYPE "operational"."claimupdatetype" AS ENUM '
        "('status_change', 'submission',"
        " 'oem_message', 'note', 'parts',"
        " 'field_visit')"
    )
    _create_tables()


def downgrade() -> None:
    _drop_tables()
    op.execute('DROP TYPE IF EXISTS "operational"."claimupdatetype"')
    op.execute('DROP TYPE IF EXISTS "operational"."claimstatus"')
