"""Warranty claim tables in project schema

Revision ID: f134a4a65238
Revises: e02ead84e542
Create Date: 2026-02-19 06:02:12.369639+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op
from sqlalchemy.schema import MetaData

# revision identifiers, used by Alembic.
revision: str = "f134a4a65238"
down_revision: str | None = "e02ead84e542"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    claim_status_enum = sa.Enum(
        "DRAFT",
        "SUBMITTED",
        "IN_PROGRESS",
        "RESOLVED",
        "CLOSED",
        name="claimstatus",
        schema="operational",
        metadata=MetaData(),
    )
    op.create_table(
        "claims",
        sa.Column("claim_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("claim_config_id", sa.Integer(), nullable=False),
        sa.Column("status", claim_status_enum, nullable=False),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("external_reference", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_config_id"],
            ["operational.claim_configs.claim_config_id"],
        ),
        sa.PrimaryKeyConstraint("claim_id"),
        schema=schema,
    )
    op.create_table(
        "claim_devices",
        sa.Column("claim_device_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("oem_serial_number", sa.String(), nullable=True),
        sa.Column("oem_part_number", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            [f"{schema}.claims.claim_id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            [f"{schema}.devices.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            [f"{schema}.events.event_id"],
        ),
        sa.PrimaryKeyConstraint("claim_device_id"),
        schema=schema,
    )
    claim_update_type_enum = sa.Enum(
        "STATUS_CHANGE",
        "SUBMISSION",
        "OEM_MESSAGE",
        "NOTE",
        "PARTS",
        "FIELD_VISIT",
        name="claimupdatetype",
        schema="operational",
        metadata=MetaData(),
    )
    op.create_table(
        "claim_updates",
        sa.Column("claim_update_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("update_type", claim_update_type_enum, nullable=False),
        sa.Column("from_status", claim_status_enum, nullable=True),
        sa.Column("to_status", claim_status_enum, nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            [f"{schema}.claims.claim_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["admin.users.user_id"],
        ),
        sa.PrimaryKeyConstraint("claim_update_id"),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claim_updates", schema=schema)
    op.drop_table("claim_devices", schema=schema)
    op.drop_table("claims", schema=schema)
    # ### end Alembic commands ###
