"""reaction col and kva capacity col

Revision ID: 4f60b0812220
Revises: 6075ef93a62b
Create Date: 2026-06-02 19:33:21.387057+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f60b0812220"
down_revision: str | None = "6075ef93a62b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("capacity_power_ac_kva", sa.REAL(), nullable=True),
        schema=schema,
    )
    op.add_column(
        "event_message_reactions",
        sa.Column("reaction_type_id", sa.Integer(), nullable=True),
        schema=schema,
    )
    op.create_foreign_key(
        op.f("event_message_reactions_reaction_type_id_fkey"),
        "event_message_reactions",
        "reaction_types",
        ["reaction_type_id"],
        ["reaction_type_id"],
        source_schema=schema,
        referent_schema="admin",
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("event_message_reactions_reaction_type_id_fkey"),
        "event_message_reactions",
        schema=schema,
        type_="foreignkey",
    )
    op.drop_column("event_message_reactions", "reaction_type_id", schema=schema)
    op.drop_column("devices", "capacity_power_ac_kva", schema=schema)
    # ### end Alembic commands ###
