"""add user_project_labels infra

Revision ID: ee077a618e7e
Revises: 1f2ee2640ca4
Create Date: 2026-03-17 16:59:06.050532+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee077a618e7e"
down_revision: str | None = "1f2ee2640ca4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_project_labels",
        sa.Column(
            "user_project_label_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "color", sa.String(length=7), server_default="#adb5bd", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["admin.users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_project_label_id"),
        sa.UniqueConstraint(
            "user_id", "name", name="uq_user_project_labels_user_id_name"
        ),
        schema="operational",
    )
    op.create_table(
        "project_labels",
        sa.Column("user_project_label_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["operational.projects.project_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_project_label_id"],
            ["operational.user_project_labels.user_project_label_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_project_label_id", "project_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_labels", schema="operational")
    op.drop_table("user_project_labels", schema="operational")
    # ### end Alembic commands ###
