"""forcast project

Revision ID: 1679c2b37f2d
Revises: f17eee401930
Create Date: 2026-05-28 05:30:09.965315+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from _alembic_migrations.tenant import for_each_project_schema
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1679c2b37f2d"
down_revision: str | None = "f17eee401930"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


@for_each_project_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast_available_pv_energy",
        sa.Column("forecast_weather_model_id", sa.Integer(), nullable=False),
        sa.Column("time_forecast_run", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_forecasted", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "p_mp",
            sa.Float(),
            nullable=False,
            comment="Available PV output power at POI [W]",
        ),
        sa.ForeignKeyConstraint(
            ["forecast_weather_model_id"],
            ["operational.forecast_weather_models.forecast_weather_model_id"],
            name=op.f("forecast_available_pv_energy_forecast_weather_model_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "forecast_weather_model_id",
            "time_forecast_run",
            "time_forecasted",
            name=op.f("forecast_available_pv_energy_pkey"),
        ),
        schema=schema,
    )
    op.execute(
        f"""
        SELECT create_hypertable(
            '{schema}.forecast_available_pv_energy',
            by_range('time_forecasted', INTERVAL '30 days'),
            create_default_indexes => FALSE
        );
        """
    )
    op.create_table(
        "forecast_available_pv_energy_latest",
        sa.Column("forecast_weather_model_id", sa.Integer(), nullable=False),
        sa.Column("time_forecast_run", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_forecasted", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "p_mp",
            sa.Float(),
            nullable=False,
            comment="Available PV output power at POI [W]",
        ),
        sa.ForeignKeyConstraint(
            ["forecast_weather_model_id"],
            ["operational.forecast_weather_models.forecast_weather_model_id"],
            name=op.f(
                "forecast_available_pv_energy_latest_forecast_weather_model_id_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "forecast_weather_model_id",
            "time_forecasted",
            name=op.f("forecast_available_pv_energy_latest_pkey"),
        ),
        schema=schema,
    )
    op.create_index(
        "forecast_available_pv_energy_latest_time_forecasted_idx",
        "forecast_available_pv_energy_latest",
        ["time_forecasted"],
        unique=False,
        schema=schema,
    )
    op.create_table(
        "forecast_met",
        sa.Column("forecast_weather_model_id", sa.Integer(), nullable=False),
        sa.Column("time_forecast_run", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_forecasted", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ghi",
            sa.Float(),
            nullable=False,
            comment="Global horizontal irradiance [W/m^2]",
        ),
        sa.Column(
            "dhi",
            sa.Float(),
            nullable=False,
            comment="Diffuse horizontal irradiance [W/m^2]",
        ),
        sa.Column(
            "dni",
            sa.Float(),
            nullable=False,
            comment="Direct normal irradiance [W/m^2]",
        ),
        sa.Column(
            "ambient_temperature",
            sa.Float(),
            nullable=False,
            comment="Ambient air temperature [C]",
        ),
        sa.Column("wind_speed", sa.Float(), nullable=False, comment="Wind speed [m/s]"),
        sa.ForeignKeyConstraint(
            ["forecast_weather_model_id"],
            ["operational.forecast_weather_models.forecast_weather_model_id"],
            name=op.f("forecast_met_forecast_weather_model_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "forecast_weather_model_id",
            "time_forecast_run",
            "time_forecasted",
            name=op.f("forecast_met_pkey"),
        ),
        schema=schema,
    )
    op.execute(
        f"""
        SELECT create_hypertable(
            '{schema}.forecast_met',
            by_range('time_forecasted', INTERVAL '30 days'),
            create_default_indexes => FALSE
        );
        """
    )
    op.create_table(
        "forecast_met_latest",
        sa.Column("forecast_weather_model_id", sa.Integer(), nullable=False),
        sa.Column("time_forecast_run", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_forecasted", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ghi",
            sa.Float(),
            nullable=False,
            comment="Global horizontal irradiance [W/m^2]",
        ),
        sa.Column(
            "dhi",
            sa.Float(),
            nullable=False,
            comment="Diffuse horizontal irradiance [W/m^2]",
        ),
        sa.Column(
            "dni",
            sa.Float(),
            nullable=False,
            comment="Direct normal irradiance [W/m^2]",
        ),
        sa.Column(
            "ambient_temperature",
            sa.Float(),
            nullable=False,
            comment="Ambient air temperature [C]",
        ),
        sa.Column("wind_speed", sa.Float(), nullable=False, comment="Wind speed [m/s]"),
        sa.ForeignKeyConstraint(
            ["forecast_weather_model_id"],
            ["operational.forecast_weather_models.forecast_weather_model_id"],
            name=op.f("forecast_met_latest_forecast_weather_model_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "forecast_weather_model_id",
            "time_forecasted",
            name=op.f("forecast_met_latest_pkey"),
        ),
        schema=schema,
    )
    op.create_index(
        "forecast_met_latest_time_forecasted_idx",
        "forecast_met_latest",
        ["time_forecasted"],
        unique=False,
        schema=schema,
    )
    op.create_table(
        "forecast_pv_energy",
        sa.Column("forecast_weather_model_id", sa.Integer(), nullable=False),
        sa.Column("time_forecast_run", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_forecasted", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "p_mp", sa.Float(), nullable=False, comment="PV output power at POI [W]"
        ),
        sa.ForeignKeyConstraint(
            ["forecast_weather_model_id"],
            ["operational.forecast_weather_models.forecast_weather_model_id"],
            name=op.f("forecast_pv_energy_forecast_weather_model_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "forecast_weather_model_id",
            "time_forecast_run",
            "time_forecasted",
            name=op.f("forecast_pv_energy_pkey"),
        ),
        schema=schema,
    )
    op.execute(
        f"""
        SELECT create_hypertable(
            '{schema}.forecast_pv_energy',
            by_range('time_forecasted', INTERVAL '30 days'),
            create_default_indexes => FALSE
        );
        """
    )
    op.create_table(
        "forecast_pv_energy_latest",
        sa.Column("forecast_weather_model_id", sa.Integer(), nullable=False),
        sa.Column("time_forecast_run", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_forecasted", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "p_mp", sa.Float(), nullable=False, comment="PV output power at POI [W]"
        ),
        sa.ForeignKeyConstraint(
            ["forecast_weather_model_id"],
            ["operational.forecast_weather_models.forecast_weather_model_id"],
            name=op.f("forecast_pv_energy_latest_forecast_weather_model_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "forecast_weather_model_id",
            "time_forecasted",
            name=op.f("forecast_pv_energy_latest_pkey"),
        ),
        schema=schema,
    )
    op.create_index(
        "forecast_pv_energy_latest_time_forecasted_idx",
        "forecast_pv_energy_latest",
        ["time_forecasted"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_project_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "forecast_pv_energy_latest_time_forecasted_idx",
        table_name="forecast_pv_energy_latest",
        schema=schema,
    )
    op.drop_table("forecast_pv_energy_latest", schema=schema)
    op.drop_table("forecast_pv_energy", schema=schema)
    op.drop_index(
        "forecast_met_latest_time_forecasted_idx",
        table_name="forecast_met_latest",
        schema=schema,
    )
    op.drop_table("forecast_met_latest", schema=schema)
    op.drop_table("forecast_met", schema=schema)
    op.drop_index(
        "forecast_available_pv_energy_latest_time_forecasted_idx",
        table_name="forecast_available_pv_energy_latest",
        schema=schema,
    )
    op.drop_table("forecast_available_pv_energy_latest", schema=schema)
    op.drop_table("forecast_available_pv_energy", schema=schema)
    # ### end Alembic commands ###
