"""add_bess_strings_bess_pcs_table

Revision ID: bcdac7962331
Revises: 995a8f6e27ba
Create Date: 2026-04-10 21:20:29.366554+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bcdac7962331"
down_revision: str | None = "995a8f6e27ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bess_pcss",
        sa.Column("bess_pcs_id", sa.Integer(), nullable=False),
        sa.Column(
            "company_id",
            sa.UUID(),
            server_default="01959294-3e51-4d3e-9f57-e9c2c3635c84",
            nullable=False,
        ),
        sa.Column("device_model_id", sa.Integer(), nullable=False),
        sa.Column("dc_voltage_min_v", sa.Float(), nullable=True),
        sa.Column("dc_voltage_max_v", sa.Float(), nullable=True),
        sa.Column("battery_voltage_min_v", sa.Float(), nullable=True),
        sa.Column("battery_voltage_max_v", sa.Float(), nullable=True),
        sa.Column("dc_current_max_a", sa.Float(), nullable=True),
        sa.Column("dc_current_per_input_a", sa.Float(), nullable=True),
        sa.Column("num_dc_inputs", sa.Integer(), nullable=True),
        sa.Column("dc_input_topology", sa.String(), nullable=True),
        sa.Column("ac_power_nominal_kw", sa.Float(), nullable=True),
        sa.Column("ac_power_max_kw", sa.Float(), nullable=True),
        sa.Column("ac_voltage_nominal_v", sa.Float(), nullable=True),
        sa.Column("ac_voltage_min_v", sa.Float(), nullable=True),
        sa.Column("ac_voltage_max_v", sa.Float(), nullable=True),
        sa.Column("ac_current_max_a", sa.Float(), nullable=True),
        sa.Column("grid_frequency_nominal_hz", sa.Float(), nullable=True),
        sa.Column("power_factor_min", sa.Float(), nullable=True),
        sa.Column("power_factor_max", sa.Float(), nullable=True),
        sa.Column("thdi_pct", sa.Float(), nullable=True),
        sa.Column("bidirectional", sa.Boolean(), nullable=True),
        sa.Column("charge_power_max_kw", sa.Float(), nullable=True),
        sa.Column("discharge_power_max_kw", sa.Float(), nullable=True),
        sa.Column("four_quadrant_operation", sa.Boolean(), nullable=True),
        sa.Column("black_start_capability", sa.Boolean(), nullable=True),
        sa.Column("grid_forming_capable", sa.Boolean(), nullable=True),
        sa.Column("grid_following_capable", sa.Boolean(), nullable=True),
        sa.Column("response_time_ms", sa.Float(), nullable=True),
        sa.Column("offgrid_supported", sa.Boolean(), nullable=True),
        sa.Column("offgrid_voltage_nominal_v", sa.Float(), nullable=True),
        sa.Column("offgrid_voltage_min_v", sa.Float(), nullable=True),
        sa.Column("offgrid_voltage_max_v", sa.Float(), nullable=True),
        sa.Column("offgrid_voltage_distortion_pct", sa.Float(), nullable=True),
        sa.Column("dc_injection_limit_pct", sa.Float(), nullable=True),
        sa.Column("unbalanced_load_capacity_pct", sa.Float(), nullable=True),
        sa.Column("efficiency_max_pct", sa.Float(), nullable=True),
        sa.Column("efficiency_cec_pct", sa.Float(), nullable=True),
        sa.Column("efficiency_european_pct", sa.Float(), nullable=True),
        sa.Column("transformer_integrated", sa.Boolean(), nullable=True),
        sa.Column("transformer_power_rating_kva", sa.Float(), nullable=True),
        sa.Column("transformer_lv_voltage_kv", sa.Float(), nullable=True),
        sa.Column("transformer_mv_voltage_kv", sa.Float(), nullable=True),
        sa.Column("transformer_vector_group", sa.String(), nullable=True),
        sa.Column("transformer_cooling_type", sa.String(), nullable=True),
        sa.Column("transformer_insulation_type", sa.String(), nullable=True),
        sa.Column("ip_rating", sa.String(), nullable=True),
        sa.Column("operating_temp_min_c", sa.Float(), nullable=True),
        sa.Column("operating_temp_max_c", sa.Float(), nullable=True),
        sa.Column("relative_humidity_max_pct", sa.Float(), nullable=True),
        sa.Column("altitude_max_m", sa.Float(), nullable=True),
        sa.Column("cooling_method", sa.String(), nullable=True),
        sa.Column("dimensions_width_mm", sa.Float(), nullable=True),
        sa.Column("dimensions_depth_mm", sa.Float(), nullable=True),
        sa.Column("dimensions_height_mm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("communication_protocols", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("supports_ieee_2030_5", sa.Boolean(), nullable=True),
        sa.Column("supports_scada", sa.Boolean(), nullable=True),
        sa.Column("ems_interface", sa.Boolean(), nullable=True),
        sa.Column("modular", sa.Boolean(), nullable=True),
        sa.Column("module_power_rating_kw", sa.Float(), nullable=True),
        sa.Column("max_system_power_kw", sa.Float(), nullable=True),
        sa.Column("containerized", sa.Boolean(), nullable=True),
        sa.Column("mv_station_integrated", sa.Boolean(), nullable=True),
        sa.Column("battery_cluster_expansion", sa.Boolean(), nullable=True),
        sa.Column("soc_balancing_support", sa.Boolean(), nullable=True),
        sa.Column("source_filename", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_model_id"],
            ["operational.device_models.device_model_id"],
        ),
        sa.PrimaryKeyConstraint("bess_pcs_id", "company_id"),
        sa.UniqueConstraint("device_model_id", "company_id"),
        schema="operational",
    )
    op.create_table(
        "bess_strings",
        sa.Column("bess_string_id", sa.Integer(), nullable=False),
        sa.Column(
            "company_id",
            sa.UUID(),
            server_default="01959294-3e51-4d3e-9f57-e9c2c3635c84",
            nullable=False,
        ),
        sa.Column("device_model_id", sa.Integer(), nullable=False),
        sa.Column("configuration", sa.String(), nullable=True),
        sa.Column("chemistry", sa.String(), nullable=True),
        sa.Column("cells_in_series", sa.Integer(), nullable=True),
        sa.Column("strings_in_parallel", sa.Integer(), nullable=True),
        sa.Column("module_count", sa.Integer(), nullable=True),
        sa.Column("nominal_energy_kwh", sa.Float(), nullable=True),
        sa.Column("nominal_power_kw", sa.Float(), nullable=True),
        sa.Column("charge_power_max_kw", sa.Float(), nullable=True),
        sa.Column("discharge_power_max_kw", sa.Float(), nullable=True),
        sa.Column("operating_voltage_min_v", sa.Float(), nullable=True),
        sa.Column("operating_voltage_max_v", sa.Float(), nullable=True),
        sa.Column("dimensions_width_mm", sa.Float(), nullable=True),
        sa.Column("dimensions_depth_mm", sa.Float(), nullable=True),
        sa.Column("dimensions_height_mm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("bms_supply_voltage_vdc", sa.Float(), nullable=True),
        sa.Column(
            "bms_cell_voltage_accuracy_mv",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("bms_total_voltage_accuracy_pct", sa.Float(), nullable=True),
        sa.Column("bms_total_voltage_detection_min_v", sa.Float(), nullable=True),
        sa.Column("bms_total_voltage_detection_max_v", sa.Float(), nullable=True),
        sa.Column("bms_current_accuracy_pct", sa.Float(), nullable=True),
        sa.Column("bms_current_min_a", sa.Float(), nullable=True),
        sa.Column("bms_current_max_a", sa.Float(), nullable=True),
        sa.Column(
            "bms_temperature_accuracy_c",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("bms_soc_accuracy_pct", sa.Float(), nullable=True),
        sa.Column("bms_soc_accuracy_notes", sa.String(), nullable=True),
        sa.Column("enclosure_rating_battery", sa.String(), nullable=True),
        sa.Column("enclosure_rating_electrical", sa.String(), nullable=True),
        sa.Column("anti_corrosion_rating", sa.String(), nullable=True),
        sa.Column("operating_temp_min_c", sa.Float(), nullable=True),
        sa.Column("operating_temp_max_c", sa.Float(), nullable=True),
        sa.Column("storage_temp_min_c", sa.Float(), nullable=True),
        sa.Column("storage_temp_max_c", sa.Float(), nullable=True),
        sa.Column("relative_humidity_min_pct", sa.Float(), nullable=True),
        sa.Column("relative_humidity_max_pct", sa.Float(), nullable=True),
        sa.Column("altitude_max_m", sa.Float(), nullable=True),
        sa.Column("thermal_management_method", sa.String(), nullable=True),
        sa.Column("auxiliary_power_phase", sa.String(), nullable=True),
        sa.Column("auxiliary_power_ac_min_v", sa.Float(), nullable=True),
        sa.Column("auxiliary_power_ac_max_v", sa.Float(), nullable=True),
        sa.Column(
            "auxiliary_power_frequency_hz",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "charge_power_limit_map",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "discharge_power_limit_map",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("standards", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_filename", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_model_id"],
            ["operational.device_models.device_model_id"],
        ),
        sa.PrimaryKeyConstraint("bess_string_id", "company_id"),
        sa.UniqueConstraint("device_model_id", "company_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bess_strings", schema="operational")
    op.drop_table("bess_pcss", schema="operational")
    # ### end Alembic commands ###
