"""Add SMS notification channel

Revision ID: 6075ef93a62b
Revises: 33a8705a0111
Create Date: 2026-06-02 03:55:31.786358+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6075ef93a62b"
down_revision: str | None = "33a8705a0111"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

notification_severity_enum = postgresql.ENUM(
    "INFO",
    "WARNING",
    "CRITICAL",
    name="notification_severity",
    schema="admin",
    create_type=False,
)

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("ALTER TYPE admin.notification_channel ADD VALUE IF NOT EXISTS 'SMS'")
    )
    op.execute(
        sa.text(
            """
            INSERT INTO admin.notification_channels (
                notification_channel_id,
                name_short
            )
            VALUES (3, 'sms')
            """
        )
    )
    op.add_column(
        "notification_preferences",
        sa.Column(
            "sms_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        schema="admin",
    )
    op.add_column(
        "notification_preferences",
        sa.Column(
            "sms_min_severity",
            notification_severity_enum,
            server_default="CRITICAL",
            nullable=False,
        ),
        schema="admin",
    )
    op.add_column(
        "notification_preferences",
        sa.Column("sms_min_severity_id", sa.Integer(), nullable=True),
        schema="admin",
    )
    op.create_foreign_key(
        op.f("notification_preferences_sms_min_severity_id_fkey"),
        "notification_preferences",
        "notification_severities",
        ["sms_min_severity_id"],
        ["notification_severity_id"],
        source_schema="admin",
        referent_schema="admin",
    )
    op.add_column(
        "notification_types",
        sa.Column(
            "sms_enabled_default",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        schema="admin",
    )
    op.add_column(
        "notification_types",
        sa.Column(
            "sms_severity_default",
            notification_severity_enum,
            nullable=True,
        ),
        schema="admin",
    )
    op.add_column(
        "notification_types",
        sa.Column("sms_severity_id_default", sa.Integer(), nullable=True),
        schema="admin",
    )
    op.create_foreign_key(
        op.f("notification_types_sms_severity_id_default_fkey"),
        "notification_types",
        "notification_severities",
        ["sms_severity_id_default"],
        ["notification_severity_id"],
        source_schema="admin",
        referent_schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("notification_types_sms_severity_id_default_fkey"),
        "notification_types",
        schema="admin",
        type_="foreignkey",
    )
    op.drop_column("notification_types", "sms_severity_id_default", schema="admin")
    op.drop_column("notification_types", "sms_severity_default", schema="admin")
    op.drop_column("notification_types", "sms_enabled_default", schema="admin")
    op.drop_constraint(
        op.f("notification_preferences_sms_min_severity_id_fkey"),
        "notification_preferences",
        schema="admin",
        type_="foreignkey",
    )
    op.drop_column("notification_preferences", "sms_min_severity_id", schema="admin")
    op.drop_column("notification_preferences", "sms_min_severity", schema="admin")
    op.drop_column("notification_preferences", "sms_enabled", schema="admin")
    op.execute(
        sa.text(
            """
            DELETE FROM admin.notification_channels
            WHERE notification_channel_id = 3
                AND name_short = 'sms'
            """
        )
    )
    # ### end Alembic commands ###
