"""Add company_id to device_models

Revision ID: d311ebc00a7e
Revises: fd675e1f21d9
Create Date: 2026-04-22 21:42:12.289071+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d311ebc00a7e"
down_revision: str | None = "fd675e1f21d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device_models",
        sa.Column("company_id", sa.UUID(), nullable=True),
        schema="operational",
    )
    op.create_foreign_key(
        None,
        "device_models",
        "companies",
        ["company_id"],
        ["company_id"],
        source_schema="operational",
        referent_schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "device_models", schema="operational", type_="foreignkey")
    op.drop_column("device_models", "company_id", schema="operational")
    # ### end Alembic commands ###
