"""adding claim_configs table and enums - other tables are in project schema
and will follow later

Revision ID: ea9eb5c0484b
Revises: 8d623f815223
Create Date: 2026-01-28 16:35:55.469051+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import MetaData

# revision identifiers, used by Alembic.
revision: str = "ea9eb5c0484b"
down_revision: str | None = "8d623f815223"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type in operational schema
    op.execute(
        'CREATE TYPE "operational"."claimsubmissionchannel" AS ENUM '
        "('email', 'portal', 'hybrid', 'unknown')"
    )

    claim_submission_channel_enum = sa.Enum(
        "email",
        "portal",
        "hybrid",
        "unknown",
        name="claimsubmissionchannel",
        schema="operational",
        metadata=MetaData(schema="operational"),
    )

    op.create_table(
        "claim_configs",
        sa.Column("claim_config_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("submitter_company_id", sa.UUID(), nullable=False),
        sa.Column("counterparty_company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "default_submission_channel",
            claim_submission_channel_enum,
            nullable=False,
        ),
        sa.Column("default_contact", sa.String(), nullable=True),
        sa.Column("portal_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["counterparty_company_id"],
            ["admin.companies.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitter_company_id"],
            ["admin.companies.company_id"],
        ),
        sa.PrimaryKeyConstraint("claim_config_id"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claim_configs", schema="operational")
    # Drop enum type from operational schema
    op.execute('DROP TYPE IF EXISTS "operational"."claimsubmissionchannel"')
    # ### end Alembic commands ###
