"""Add projects.database_provider

Revision ID: 8196b88aee40
Revises: 6e740aeff77f
Create Date: 2026-01-14 05:56:35.341139+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8196b88aee40"
down_revision: str | None = "6e740aeff77f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE projectdatabaseprovider AS ENUM ('timescale', 'clickhouse')"
    )
    op.add_column(
        "projects",
        sa.Column(
            "database_provider",
            sa.Enum("timescale", "clickhouse", name="projectdatabaseprovider"),
            server_default="clickhouse",
            nullable=False,
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "database_provider", schema="operational")
    op.execute("DROP TYPE IF EXISTS projectdatabaseprovider")
    # ### end Alembic commands ###
