"""operational active events

Revision ID: e73126f587ad
Revises: 1679c2b37f2d
Create Date: 2026-05-28 19:46:54.606352+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e73126f587ad"
down_revision: str | None = "1679c2b37f2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_events",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("device_type_id", sa.Integer(), nullable=False),
        sa.Column("device_name_full", sa.String(), nullable=False),
        sa.Column("failure_mode_id", sa.Integer(), nullable=False),
        sa.Column("root_cause_id", sa.Integer(), nullable=True),
        sa.Column("time_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("loss_total_financial", sa.Double(), nullable=True),
        sa.Column("loss_total_energetic", sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_type_id"],
            ["operational.device_types.device_type_id"],
            name=op.f("active_events_device_type_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["operational.failure_modes.failure_mode_id"],
            name=op.f("active_events_failure_mode_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["operational.projects.project_id"],
            name=op.f("active_events_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["root_cause_id"],
            ["operational.root_causes.root_cause_id"],
            name=op.f("active_events_root_cause_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "event_id", name=op.f("active_events_pkey")
        ),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("active_events", schema="operational")
    # ### end Alembic commands ###
