"""add 4 threshold fields to kpi type table

Revision ID: 6e740aeff77f
Revises: 950cfa882dd4
Create Date: 2026-01-09 00:11:00.041744+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e740aeff77f"
down_revision: str | None = "950cfa882dd4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema`
#   arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kpi_types",
        sa.Column("critical_low", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "kpi_types",
        sa.Column("warning_low", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "kpi_types",
        sa.Column("warning_high", sa.Float(), nullable=True),
        schema="operational",
    )
    op.add_column(
        "kpi_types",
        sa.Column("critical_high", sa.Float(), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kpi_types", "critical_high", schema="operational")
    op.drop_column("kpi_types", "warning_high", schema="operational")
    op.drop_column("kpi_types", "warning_low", schema="operational")
    op.drop_column("kpi_types", "critical_low", schema="operational")
    # ### end Alembic commands ###
