"""Add unique constraint to project.project_id_int

Revision ID: 950cfa882dd4
Revises: 40f280a6dc95
Create Date: 2026-01-07 20:48:48.341154+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "950cfa882dd4"
down_revision: str | None = "40f280a6dc95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "projects", ["project_id_int"], schema="operational"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", schema="operational", type_="unique")
    # ### end Alembic commands ###
