"""forcast operational

Revision ID: f17eee401930
Revises: 84e7ba624e4f
Create Date: 2026-05-27 22:36:29.574969+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f17eee401930"
down_revision: str | None = "84e7ba624e4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast_weather_providers",
        sa.Column(
            "forecast_weather_provider_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.Column("is_public", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.PrimaryKeyConstraint(
            "forecast_weather_provider_id", name=op.f("forecast_weather_providers_pkey")
        ),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    op.create_table(
        "forecast_weather_models",
        sa.Column(
            "forecast_weather_model_id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("forecast_weather_provider_id", sa.Integer(), nullable=False),
        sa.Column("name_short", sa.String(), nullable=False),
        sa.Column("name_long", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_weather_provider_id"],
            ["operational.forecast_weather_providers.forecast_weather_provider_id"],
            name=op.f("forecast_weather_models_forecast_weather_provider_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "forecast_weather_model_id", name=op.f("forecast_weather_models_pkey")
        ),
        sa.UniqueConstraint("name_short"),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forecast_weather_models", schema="operational")
    op.drop_table("forecast_weather_providers", schema="operational")
    # ### end Alembic commands ###
