"""naming convention

Revision ID: 84e7ba624e4f
Revises: a9b8c7d6e5f4
Create Date: 2026-05-26 02:41:45.710129+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84e7ba624e4f"
down_revision: str | None = "a9b8c7d6e5f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Remember to remove any operations unrelated to your migration!
# Are you making changes to the project schemas?
#   If so, pass the `schema` arg to all operations (`op` functions)
#   If not, remove the `for_each_project_schema` decorator and `schema` arg in
#     `upgrade` and `downgrade` functions


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("notification_preferences_user_id_project_id_notification_ty_key"),
        "notification_preferences",
        schema="admin",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("notification_preferences_user_id_project_id_notification_type_id_key"),
        "notification_preferences",
        ["user_id", "project_id", "notification_type_id"],
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("notification_preferences_user_id_project_id_notification_type_id_key"),
        "notification_preferences",
        schema="admin",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("notification_preferences_user_id_project_id_notification_ty_key"),
        "notification_preferences",
        ["user_id", "project_id", "notification_type_id"],
        schema="admin",
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
