name: API Google Chat Notifications

on:
  pull_request:
    types: [closed]
    paths:
      - 'api/**'
      - '.github/workflows/api-google-chat-notifications.yml'

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Google Chat if key merge
        env:
          CHAT_WEBHOOK: ${{ secrets.DEPLOYMENTS_BOT_URL }}
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
          AWS_STAGING_URL: ${{ secrets.EB_STAGING_URL }}
          AWS_MAIN_URL: ${{ secrets.EB_PROD_URL }}
        run: |
          if [[ "$BASE_BRANCH" == "main" && "$HEAD_BRANCH" == "staging" ]]; then
            DEPLOYMENT_URL="$AWS_MAIN_URL"
          elif [[ "$BASE_BRANCH" == "staging" && "$HEAD_BRANCH" == "dev" ]] || \
               [[ "$BASE_BRANCH" == "dev" ]]; then
            DEPLOYMENT_URL="$AWS_STAGING_URL"
          fi

          if [[ "$BASE_BRANCH" == "main" && "$HEAD_BRANCH" == "staging" ]] || \
             [[ "$BASE_BRANCH" == "staging" && "$HEAD_BRANCH" == "dev" ]]; then

            curl -X POST "$CHAT_WEBHOOK" \
              -H 'Content-Type: application/json' \
              -d "{
                \"text\": \"🔀 *PR merged in \`api\`*: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})>\n📍 Merged from *${HEAD_BRANCH}* into *${BASE_BRANCH}* by *${{ github.actor }}*\n🚀 <${DEPLOYMENT_URL}|View Deployment>\"
              }"
          else
            echo "Merge not from dev→staging or staging→main; skipping."
          fi
